// vueui/src/components/view/machinery/power/apc.vue
<template>
  <div>
    <div v-if="failTime" class="notice"> <!-- Failure - Disabled -->
      <h3 class="fw-bold">SYSTEM FAILURE</h3>
      <span class="fst-italic">I/O regulator malfuction detected! Waiting for system reboot...</span><br>
      Automatic reboot in {{failTime}} seconds...
      <vui-button icon="sync" :params="{reboot : 1}">Reboot Now</vui-button>
    </div>
    <vui-group v-else> <!-- Main -->
      <div class="notice"> <!-- Lock -->
        <div v-if="siliconUser">
          <vui-group-item label="Interface Lock:">
            <vui-button icon="lock" :params="{toggleaccess : 1}" :class="{selected : locked}">Engaged</vui-button>
            <vui-button icon="lock-open" :params="{toggleaccess : 1}" :disabled="malfstatus >= 2" :class="{selected : (malfstatus < 2) && !locked}">Disengaged</vui-button>
          </vui-group-item>
        </div>
        <span v-else>Swipe an ID card to {{locked ? 'un' : null}}lock this interface.</span>
      </div>

      <div style="min-width: 480px"> <!-- Body -->
        <h3>Power Status</h3>
        <vui-group-item label="Main Breaker:">
          <div v-if="locked && !siliconUser">
            <span :class="{good : isOperating, bad : !isOperating}">{{isOperating ? 'On' : 'Off'}}</span>
          </div>
          <div v-else>
            <vui-button icon="times" :params="{breaker : 1}" v-if="!isOperating">Off</vui-button>
            <vui-button icon="power" :params="{breaker : 1}" v-else>On</vui-button>
          </div>
        </vui-group-item>

        <vui-group-item label="External Power:">
          <span v-if="externalPower == 2" class="good">Good</span>
          <span v-else-if="externalPower == 1" class="average">Low</span>
          <span v-else class="bad">None</span>
        </vui-group-item>

        <vui-group-item label="Power Cell">
          <span v-if="powerCellStatus == null" class="bad">Power cell removed.</span>
          <span v-else>
            <vui-progress :value="powerCellStatus" :min="0" :max="100" :class="cellClass"/>
            <span style="width:60px">{{Math.round(powerCellStatus * 10)/10}}%</span>
          </span>
        </vui-group-item>

        <vui-group-item label="Power Cell charge status:">
          <div class="statusValue">
            <span v-if="charge_mode == 1">APC's power cell will be fully charged in {{timeRemaining}}.</span>
            <span v-else-if="charge_mode == 2">APC is not charging or discharging.</span>
            <span v-else>APC will run out of charge in {{timeRemaining}}.</span>
          </div>
        </vui-group-item>

        <vui-group-item label="Charge Mode:" v-if="powerCellStatus != null">
          <span v-if="locked && !siliconUser" :class="{good : chargeMode, bad : !chargeMode}">{{chargeMode ? "Auto" : "Off"}}</span>
          <vui-button v-else :icon="chargeMode ? 'sync' : 'times'" :params="{cmode : 1}">{{chargeMode ? 'Auto' : 'Off'}}</vui-button>
          &nbsp;
          [<span :class="chargeClass">{{chargeStatus}}</span>]
        </vui-group-item>

        <vui-group-item label="Night Lighting:">
          <vui-button :icon="lightingMode ? 'moon' : 'times'" :params="{lmode : lightingMode ? 'off' : 'on'}">
            {{lightingMode ? 'On' : 'Off'}}
          </vui-button>
        </vui-group-item>

        <vui-group-item label="Emergency Lighting:">
          <div style="width: 105px">
            <span v-if="locked && !siliconUser">{{emergencyMode ? "On" : "Off"}}</span>
            <vui-button v-else icon="lightbulb" :params="{emergency_lights : 1}">{{emergencyMode ? 'On' : 'Off'}}</vui-button>
          </div>
        </vui-group-item>

        <h3>Power Channels</h3>
        <vui-group-item v-for="(channel, channel_title) in powerChannels" :key="channel_title" :label="channel_title">
          <span style="width: 70px; text-align: right">
            {{channel.powerLoad}}&nbsp;W
          </span>
          <span style="width: 105px">
            &nbsp;&nbsp;
            <span :class="channelStatClass(channel.status)">{{channelStatus(channel.status)}}</span>
            <span v-if="locked">
              <span v-if="channel.status == 1 || channel.status == 3">
                &nbsp;&nbsp;{{channelPower(channel.status)}}
              </span>
            </span>
          </span>
          <div v-if="!locked || siliconUser">
            <vui-button icon="sync" :params="{set : 3, chan : channel_title}" :class="{selected : channel.status == 1 || channel.status == 3}">Auto</vui-button>
            <vui-button icon="power" :params="{set : 2, chan : channel_title}" :class="{selected : channel.status == 2}">On</vui-button>
            <vui-button icon="times" :params="{set : 1, chan : channel_title}" :class="{selected : channel.status == 0}">Off</vui-button>
          </div>
        </vui-group-item>

        <vui-group-item label="Total Load:">
          {{totalLoad}}W{{totalCharging ? ` (+ ${totalCharging}W Charging)` : null}}
        </vui-group-item>

        <vui-group-item :balance="0.69">&nbsp;</vui-group-item>

        <vui-group-item label="Cover Lock">
          <div v-if="locked && !siliconUser">
            <span :class="{good : coverLocked, bad : !coverLocked}" v-if="coverLocked">{{coverLocked ? 'Engaged' : 'Disengaged'}}</span>
          </div>
          <div v-else>
            <vui-button :icon="(coverLocked ? 'un' : null) + locked" :params="{lock : 1}">{{coverLocked ? 'E' : 'Dise'}}ngaged</vui-button>
          </div>
        </vui-group-item>

        <div v-if="siliconUser">
          <h3>System Overrides</h3>
          <div>
            <vui-button icon="lightbulb" :params="{overload : 1}">Overload Lighting Circuit</vui-button>
            <vui-button v-if="malfStatus == 1" icon="script" :params="{malfhack : 1}">Override Programming</vui-button>
            <span class="notice" v-else-if="malfStatus > 1">APC Hacked</span>
          </div>
        </div>
      </div>
    </vui-group>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state; // Make data more easily accessible
  },
  computed: {
    chargeClass() {
      if(this.chargingStatus > 1) {return "good"}
      if(this.chargingStatus == 1) {return "average"}
      return "bad";
    },
    chargeStatus() {
      if(this.chargingStatus > 1) {return "Fully Charged"}
      if(this.chargingStatus == 1) {return "Charging"}
      return "Not Charging";
    },
    cellClass() {
      if(this.powerCellStatus >= 50) {return "good"}
      if(this.powerCellStatus >= 25) {return "average"}
      return "bad";
    },
    timeRemaining() {
      var hours = Math.round(this.time / 3600)
      var minutes = Math.round(this.time % 3600 / 60)
      var seconds = Math.round(this.time % 60)
      return [hours >= 1 && `${hours} hours`, minutes >= 1 && `${minutes} minutes`, seconds >= 1 && `${seconds} seconds`].filter(Boolean).join(", ")
    }
  },
  methods: {
    channelStatus(channelStat) {
      if(channelStat <= 1) {return "Off"}
      return "On";
    },
    channelPower(channelStat) {
      if(channelStat == 1 || channelStat == 3) {return "Auto"}
      return "Manual";
    },
    channelStatClass(channelStat) {
      if(channelStat <= 1) {return "Off"}
      return "On";
    },
  }
}
</script>

// tgui/packages/tgui/interfaces/Apc.tsx
import { BooleanLike } from '../../common/react';
import { useBackend } from '../backend';
import { Section, Box, Button, BlockQuote, LabeledList, ProgressBar } from '../components';
import { Window } from '../layouts';

export type APCData = {
  locked: BooleanLike;
  power_cell_status: number;
  fail_time: number;
  silicon_user: BooleanLike;
  total_load: number;
  total_charging: number;
  is_operating: BooleanLike;
  external_power: number;
  charge_mode: BooleanLike;
  main_status: number;
  lighting_mode: BooleanLike;
  charging_status: number;
  cover_locked: BooleanLike;
  emergency_mode: BooleanLike;
  time: number;
  power_channels: PowerChannel[];
};

type PowerChannel = {
  name: string;
  power_load: number;
  status: number;
};

export const Apc = (props, context) => {
  const { act, data } = useBackend<APCData>(context);

  return (
    <Window resizable>
      <Window.Content scrollable>
        {data.fail_time > 0 ? <FailWindow /> : <APCWindow />}
      </Window.Content>
    </Window>
  );
};

export const FailWindow = (props, context) => {
  const { act, data } = useBackend<APCData>(context);

  return (
    <Section
      title="SYSTEM FAILURE"
      buttons={
        <Button
          content="Reboot Now"
          icon="sync"
          color="bad"
          onClick={() => act('reboot')}
        />
      }>
      <Box color="red">
        I/O regulator malfuction detected! Waiting for system reboot...
      </Box>
      <BlockQuote>Automatic reboot in {data.fail_time} seconds...</BlockQuote>
    </Section>
  );
};

export const APCWindow = (props, context) => {
  const { act, data } = useBackend<APCData>(context);
  return (
    <Section>
      {data.silicon_user ? (
        <SiliconWindow />
      ) : (
        <BlockQuote>
          Swipe an ID card to {data.locked ? 'un' : ''}lock this interface.
        </BlockQuote>
      )}
      <Section title="Power Status">
        <LabeledList>
          <LabeledList.Item label="Main Breaker">
            {data.locked && !data.silicon_user ? (
              <Box color={data.is_operating ? 'good' : 'bad'}>
                {data.is_operating ? 'On' : 'Off'}
              </Box>
            ) : (
              <Button
                content={data.is_operating ? 'On' : 'Off'}
                icon={data.is_operating ? 'power-off' : 'times'}
                color={data.is_operating ? 'good' : 'bad'}
                onClick={() => act('breaker')}
              />
            )}
          </LabeledList.Item>
          <LabeledList.Item label="External Power">
            {data.external_power === 2 ? (
              <Box color="good">Good</Box>
            ) : data.external_power === 1 ? (
              <Box color="average">Low</Box>
            ) : (
              <Box color="bad">None</Box>
            )}
          </LabeledList.Item>
          <LabeledList.Item label="Power Cell">
            {data.power_cell_status ? (
              <ProgressBar
                ranges={{
                  good: [75, 100],
                  average: [30, 75],
                  bad: [0, 30],
                }}
                value={data.power_cell_status}
                minValue={0}
                maxValue={100}
              />
            ) : (
              <Box color="bad">Power cell removed.</Box>
            )}
          </LabeledList.Item>
          {data.power_cell_status ? (
            <LabeledList.Item label="Charge Mode">
              {!data.silicon_user && data.locked ? (
                <Box color={data.charge_mode ? 'good' : 'bad'}>
                  {data.charge_mode ? 'Auto' : 'Off'}
                </Box>
              ) : (
                <Box>
                  <Button
                    content={data.charge_mode ? 'Auto' : 'Off'}
                    icon={data.charge_mode ? 'sync' : 'times'}
                    color={data.charge_mode ? 'good' : ''}
                    onClick={() => act('cmode')}
                  />
                  <Box as="span" color={ChargeClass(data.charging_status)}>
                    [{ChargeStatus(data.charging_status)}]
                  </Box>
                </Box>
              )}
            </LabeledList.Item>
          ) : (
            ''
          )}
          <LabeledList.Item label="Night Lighting">
            <Button
              content={data.lighting_mode ? 'On' : 'Off'}
              icon={data.lighting_mode ? 'moon' : 'sun'}
              color={data.lighting_mode ? 'good' : ''}
              onClick={() =>
                act('lmode', { lmode: data.lighting_mode ? 'off' : 'on' })
              }
            />
          </LabeledList.Item>
          <LabeledList.Item label="Emergency Lighting">
            {!data.silicon_user && data.locked ? (
              <Box>{data.emergency_mode ? 'On' : 'Off'}</Box>
            ) : (
              <Button
                content={data.emergency_mode ? 'On' : 'Off'}
                icon="lightbulb"
                color={data.emergency_mode ? 'good' : ''}
                onClick={() => act('emergency_lights')}
              />
            )}
          </LabeledList.Item>
        </LabeledList>
      </Section>
      <Section title="Power Channels">
        <LabeledList>
          {data.power_channels.map((channel) => (
            <LabeledList.Item label={channel.name} key={channel.name}>
              <Box color={channelStatClass(channel.status)}>
                [{channelStatus(channel.status)}] | [
                {channelPower(channel.status)}] | {channel.power_load} W
              </Box>
              {!data.locked && !data.silicon_user ? (
                <Section>
                  <Button
                    content="Auto"
                    icon="sync"
                    color={
                      channel.status === 1 || channel.status === 3 ? 'good' : ''
                    }
                    onClick={() => act('set', { set: 3, chan: channel.name })}
                  />
                  <Button
                    content="On"
                    icon="power-off"
                    color={channel.status === 2 ? 'good' : ''}
                    onClick={() => act('set', { set: 2, chan: channel.name })}
                  />
                  <Button
                    content="Off"
                    icon="times"
                    color={channel.status === 0 ? 'good' : ''}
                    onClick={() => act('set', { set: 1, chan: channel.name })}
                  />
                </Section>
              ) : (
                ''
              )}
            </LabeledList.Item>
          ))}
          <LabeledList.Item label="Total Load">
            {data.total_load}W
            {data.total_charging
              ? ` (+ ${data.total_charging}W Charging)`
              : null}
          </LabeledList.Item>
        </LabeledList>
      </Section>
      <Section title="Lock">
        <LabeledList>
          <LabeledList.Item label="Cover Lock">
            {data.locked && !data.silicon_user ? (
              <Box color={data.cover_locked ? 'good' : 'bad'}>
                {data.cover_locked ? 'E' : 'Dise'}ngaged
              </Box>
            ) : (
              <Button
                content={data.cover_locked ? 'Engaged' : 'Disengaged'}
                icon={data.cover_locked ? 'lock' : 'lock-open'}
                color={data.cover_locked ? 'good' : 'bad'}
                onClick={() => act('lock')}
              />
            )}
          </LabeledList.Item>
        </LabeledList>
      </Section>
      {data.silicon_user ? (
        <Section title="System Overrides">
          <Button
            content="Overload Lighting Circuit"
            icon="lightbulb"
            onClick={() => act('overload')}
          />
        </Section>
      ) : (
        ''
      )}
    </Section>
  );
};

export const SiliconWindow = (props, context) => {
  const { act, data } = useBackend<APCData>(context);
  return (
    <Section
      title="Interface Lock"
      buttons={
        <Button
          content={data.locked ? 'Engaged' : 'Disengaged'}
          icon={data.locked ? 'lock' : 'lock-open'}
          color={data.locked ? 'good' : 'bad'}
          onClick={() => act('toggleaccess')}
        />
      }
    />
  );
};

const ChargeStatus = (value) => {
  if (value > 1) {
    return 'Fully Charged';
  } else if (value === 1) {
    return 'Charging';
  } else return 'Not Charging';
};

const ChargeClass = (value) => {
  if (value > 1) {
    return 'good';
  } else if (value === 1) {
    return 'average';
  } else return 'bad';
};

const channelStatus = (channelStat) => {
  if (channelStat <= 1) {
    return 'Off';
  } else return 'On';
};

const channelPower = (channelStat) => {
  if (channelStat === 1 || channelStat === 3) {
    return 'Auto';
  }
  return 'Manual';
};

const channelStatClass = (channelStat) => {
  if (channelStat <= 1) {
    return 'bad';
  }
  return 'good';
};
