// vueui/src/components/view/medical/bodyscanner.vue
<template>
  <div>

    <!-- Errors -->
    <div v-if="invalid" class="center">
      <span class="red" v-if="nocons">Error: No scanner bed detected!</span>
      <span class="red" v-else-if="!occupied">No occupant detected.</span>
      <span class="red" v-else-if="ipc">Error: Object in scanner bed interfering with sensor array.</span>
      <span class="red" v-else-if="noscan">Error: No diagnostics profile installed for this species.</span>
      <span class="red" v-else>Error: Unknown error.</span>
    </div>

    <!-- Health Display -->
    <table class="bodyscanner" v-else>
      <div class="row">

        <!-- Left Side -->
        <div class="column">
          <h3>Patient Status</h3>
          <hr>

          <!-- Patient Details -->
          <vui-group>
            <vui-group-item label="Name:">{{ name }}</vui-group-item>
            <vui-group-item label="Status:"><span :style="{color:consciousnessLabel(stat)}">{{ consciousnessText(stat) }}</span></vui-group-item>
            <vui-group-item label="Species:">{{ species }}</vui-group-item>
            <vui-group-item label="Brain Activity:"><vui-progress :class="progressClass(brain_activity)" :value="brain_activity">{{brain_activity}}%</vui-progress></vui-group-item>

            <!-- Trauma -->
            <template v-if="stat < 2">
              <vui-group-item label="Physical Trauma:"><span :style="{color:damageLabel(bruteLoss)}">{{ bruteLoss }}</span></vui-group-item>
              <vui-group-item label="Oxygen Deprivation:"><span :style="{color:damageLabel(oxyLoss)}">{{ oxyLoss }}</span></vui-group-item>
              <vui-group-item label="Organ Failure:"><span :style="{color:damageLabel(toxLoss)}">{{ toxLoss }}</span></vui-group-item>
              <vui-group-item label="Burn Severity:"><span :style="{color:damageLabel(fireLoss)}">{{ fireLoss }}</span></vui-group-item>
            </template>
          </vui-group>
          <hr>

          <!-- Status Effects -->
          <vui-group>
            <vui-group-item label="Radiation Level:">{{ Math.round(rads) }}</vui-group-item>
            <vui-group-item label="Genetic Damage:">{{ cloneLoss }}</vui-group-item>
            <vui-group-item label="Est. Paralysis Level:">{{ paralysis }}<span v-if="paralysis"> (~{{ Math.round(paralysis/4) }} Seconds Left)</span></vui-group-item>
            <vui-group-item label="Body Temperature:">{{bodytemp}} K (~ {{Math.round(bodytemp - 273.15)}} C)</vui-group-item>
          </vui-group>

          <!-- Blood -->
          <hr>
          <h3>Blood Status</h3>
          <hr>
          <vui-group>
            <vui-group-item label="BP:" :style="{color:getPressureClass(blood_pressure_level)}"> {{blood_pressure}} </vui-group-item>
            <vui-group-item label="Blood Oxygenation:"><vui-progress :class="progressClass(brain_activity)" :value="Math.round(blood_o2)">{{Math.round(blood_o2)}}%</vui-progress></vui-group-item>
            <vui-group-item label="Blood Volume:"><vui-progress :class="progressClass(brain_activity)" :value="Math.round(blood_volume)">{{Math.round(blood_volume)}}%</vui-progress></vui-group-item>
            <vui-group-item label="Inaprovaline:" v-if="Math.round(norepiAmt)"> {{ Math.round(norepiAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Soporific:" v-if="Math.round(soporAmt)"> {{ Math.round(soporAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Bicaridine:" v-if="Math.round(bicardAmt)"> {{ Math.round(bicardAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Dermaline:" v-if="Math.round(dermAmt)"> {{ Math.round(dermAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Dexalin:" v-if="Math.round(dexAmt)"> {{ Math.round(dexAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Thetamycin:" v-if="Math.round(thetaAmt)"> {{ Math.round(thetaAmt) }} unit(s)</vui-group-item>
            <vui-group-item label="Other:" v-if="Math.round(otherAmt)"> {{ Math.round(otherAmt) }} unit(s)</vui-group-item>
          </vui-group>
        </div>

        <!-- Right Side -->
        <div class="column">

          <!-- Missing Organs -->
          <template v-if="hasmissing">
            <div v-for="organ in missingparts" :key="organ.name">
              <vui-group-item> {{ organ }} </vui-group-item>
            </div>
          </template>

          <!-- Internal Organs -->
          <h3>Internal Organ Status</h3>
          <hr>
          <table class="injury">
            <template v-if="hasinternalinjury">
              <tr>
                <th>Organ</th>
                <th>Trauma</th>
                <th>Wounds</th>
                <th>Location</th>
              </tr>
            </template>
            <template v-else>
              <tr>
                <th><span style="color:LimeGreen">The occupant has no internal injuries.</span></th>
              </tr>
            </template>
            <tr v-for="organ in organs" :key="organ.name">
              <template v-if="organ.damage != 'None' || organ.hasWounds">
                <td> {{ organ.name }} </td>
                <td><span :style="{color:damageLabel(organ.damage)}"> {{ organ.damage }}</span></td>
                <td><div v-for="wound in organ.wounds" :key="wound.name" style="color:Tomato"> {{ wound }} </div></td>
                <td> {{ organ.location }} </td>
              </template>
            </tr>
          </table>

          <!-- External Organs -->
          <hr>
          <h3>External Bodypart Status</h3>
          <hr>
          <table class="injury">
            <template v-if="hasexternalinjury">
              <tr>
                <th>Organ</th>
                <th>Physical / Burn Trauma</th>
                <th>Wounds</th>
              </tr>
            </template>
            <template v-else>
              <tr>
                <th><span style="color:LimeGreen">The occupant has no external injuries.</span></th>
              </tr>
            </template>
            <tr v-for="organ in bodyparts" :key="organ.name">
              <template v-if="organ.bruteDmg != 'None' || organ.burnDmg != 'None' || organ.hasWounds">
                <td> {{ organ.name }} </td>
                <td><span :style="{color:damageLabel(organ.bruteDmg)}"> {{ organ.bruteDmg }} </span> / <span :style="{color:damageLabel(organ.burnDmg)}"> {{ organ.burnDmg }} </span></td>
                <td><div v-for="wound in organ.wounds" :key="wound.name" style="color:Tomato"> {{ wound }} </div></td>
              </template>
            </tr>
          </table>
        </div>

        <h3>Actions</h3>
        <vui-button class="center" :params="{print: 1}">Print Report</vui-button>
        <vui-button class="center" :params="{eject: 1}">Eject Occupant</vui-button>

      </div>
    </table>
  </div>
</template>


<script>
  export default {
    data() {
      return this.$root.$data.state;
    },
    methods: {
    consciousnessLabel(value) {
      switch (value) {
        case 0:
          return "LimeGreen"
        case 1:
          return "OrangeRed"
        case 2:
          return "Crimson"
        }
      },
      consciousnessText(value) {
      switch (value) {
        case 0:
          return "Conscious"
        case 1:
          return "Unconscious"
        case 2:
          return "DEAD"
        }
      },
    progressClass(value) {
      if (value <= 50) {
        return "bad"
      }
      else if (value <= 90) {
        return "average"
      }
      else {
        return "good"
      }
    },
    brainText(value) {
      switch (value) {
        case 0:
          return "None, patient is braindead"
        case -1:
          return "ERROR - Nonstandard biology"
        default:
          return value.toString().concat("%");
        }
      },
    damageLabel(value) {
      if(value == "Fatal" || value < 10) {
        return "Crimson"
      }
      if(value == "Critical" || value < 20) {
        return "Crimson"
      }
      else if(value == "Severe" || value < 40) {
        return "OrangeRed"
      }
      else if(value == "Significant" || value < 60) {
        return "Tomato"
      }
      else if(value == "Moderate" || value < 80) {
        return "Orange"
      }
      else if(value == "Minor" || value < 100) {
        return "LawnGreen"
      }
      else {
        return "LimeGreen"
      }
    },
    getPressureClass(tpressure) {
      switch (tpressure) {
        case 1:
          return "Crimson"
        case 2:
          return "LimeGreen"
        case 3:
          return "LawnGreen"
        case 4:
          return "Crimson"
        default:
          return "LightSkyBlue"
      }
    },
  }
}
</script>

<style lang="scss" scoped>
.bodyscanner {
  display: table;
  width: 100%;

  .header {
    display: table-row;
    .header-item, .item {
      display: table-cell;
      padding: 1px;
      vertical-align: middle;
    }
  }

  .column {
    float: left;
    width: 45%;
    margin: 1%;
    padding: 10px;
    outline-style: ridge;
    outline-color: black;
    background-color: rgba(0, 0, 0, 0.4);
    height: 500px;
    overflow: auto;
  }

  /* Clear floats after the columns */
  .row:after {
    content:"";
    display: table;
    clear: both;
  }
}

.left {
  text-align: left;
}

.center {
  text-align: center;
}

.right {
  text-align: right;
}

table .injury {
  border-spacing: 20px 0;
}

td, th {
  text-align: center;
}
</style>

// tgui/packages/tgui/interfaces/BodyScanner.tsx
import { BooleanLike } from '../../common/react';
import { useBackend } from '../backend';
import { BlockQuote, Button, LabeledList, Section, Table } from '../components';
import { Window } from '../layouts';

export type ScannerData = {
  // Booleans for errors.
  noscan: BooleanLike;
  nocons: BooleanLike;
  occupied: BooleanLike;
  invalid: BooleanLike;
  ipc: BooleanLike;

  // Occupant data.
  stat: number;
  name: string;
  species: string;
  brain_activity: number;
  pulse: number;
  blood_pressure: number;
  blood_pressure_level: number;
  blood_volume: number;
  blood_o2: number;
  rads: number;

  cloneLoss: string;
  oxyLoss: string;
  bruteLoss: string;
  fireLoss: string;
  toxLoss: string;

  paralysis: number;
  bodytemp: number;
  inaprovaline_amount: number;
  soporific_amount: number;
  bicaridine_amount: number;
  dexalin_amount: number;
  dermaline_amount: number;
  thetamycin_amount: number;
  other_amount: number;

  bodyparts: Organ[];
  organs: InternalOrgan[];
  has_internal_injuries: BooleanLike;
  has_external_injuries: BooleanLike;
  missing_organs: string;
};

type Organ = {
  name: string;
  burn_damage: string;
  brute_damage: string;
  wounds: string;
};

type InternalOrgan = {
  name: string;
  location: string;
  damage: string;
  wounds: string;
};

export const BodyScanner = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <Window resizable theme="zenghu">
      <Window.Content scrollable>
        {data.invalid ? <InvalidWindow /> : <ScannerWindow />}
      </Window.Content>
    </Window>
  );
};

export const InvalidWindow = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <BlockQuote color="bad">
      {data.nocons
        ? 'No scanner bed detected.'
        : !data.occupied
          ? 'No occupant detected.'
          : data.ipc
            ? 'An object in the scanner bed is interfering with the sensor array.'
            : data.noscan
              ? 'No diagnostics profile installed for this species.'
              : 'Unknown error.'}
    </BlockQuote>
  );
};

export const ScannerWindow = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <Table>
      <Table.Row>
        <Table.Cell>
          <Section fill={0} title="Patient Status" scrollable>
            <LabeledList>
              <LabeledList.Item label="Name">{data.name}</LabeledList.Item>
              <LabeledList.Item
                label="Status"
                color={consciousnessLabel(data.stat)}>
                {consciousnessText(data.stat)}
              </LabeledList.Item>
              <LabeledList.Item label="Species">
                {data.species}
              </LabeledList.Item>
              <LabeledList.Item
                label="Brain Activity"
                color={progressClass(data.brain_activity)}>
                {brainText(data.brain_activity)}
              </LabeledList.Item>
              {data.stat < 2 ? <TraumaInfo /> : ''}
            </LabeledList>
            <LabeledList>
              <LabeledList.Divider size={1} />
              <LabeledList.Item label="Radiation Level">
                {Math.round(data.rads)} Gy
              </LabeledList.Item>
              <LabeledList.Item label="Genetic Damage">
                {data.cloneLoss}
              </LabeledList.Item>
              <LabeledList.Item label="Est. Paralysis Level">
                {data.paralysis
                  ? Math.round(data.paralysis / 4) + ' Seconds Left'
                  : 'No paralysis detected.'}
              </LabeledList.Item>
              <LabeledList.Item label="Body Temperature">
                {data.bodytemp}
              </LabeledList.Item>
            </LabeledList>
            <Section title="Blood Status" fill:true>
              <LabeledList>
                <LabeledList.Item
                  label="BP"
                  color={getPressureClass(data.blood_pressure_level)}>
                  {data.blood_pressure}
                </LabeledList.Item>
                <LabeledList.Item
                  label="Blood Oxygenation"
                  color={progressClass(data.brain_activity)}>
                  {Math.round(data.blood_o2)}%
                </LabeledList.Item>
                <LabeledList.Item
                  label="Blood Volume"
                  color={progressClass(data.brain_activity)}>
                  {Math.round(data.blood_volume)}%
                </LabeledList.Item>
                {data.inaprovaline_amount ? (
                  <LabeledList.Item label="Inaprovaline">
                    {Math.round(data.inaprovaline_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.soporific_amount ? (
                  <LabeledList.Item label="Soporific">
                    {Math.round(data.soporific_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.bicaridine_amount ? (
                  <LabeledList.Item label="Bicaridine">
                    {Math.round(data.bicaridine_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.dermaline_amount ? (
                  <LabeledList.Item label="Dermaline">
                    {Math.round(data.dermaline_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.dexalin_amount ? (
                  <LabeledList.Item label="Dexalin">
                    {Math.round(data.dexalin_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.thetamycin_amount ? (
                  <LabeledList.Item label="Thetamycin">
                    {Math.round(data.thetamycin_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
                {data.other_amount ? (
                  <LabeledList.Item label="Other">
                    {Math.round(data.other_amount)}u
                  </LabeledList.Item>
                ) : (
                  ''
                )}
              </LabeledList>
            </Section>
          </Section>
        </Table.Cell>
        <Table.Cell nowrap>
          <Section
            title="Organ Status"
            scrollable
            buttons={
              <>
                <Button
                  content="Print Report"
                  icon="calendar"
                  onClick={() => act('print')}
                />
                <Button
                  content="Eject Occupant"
                  icon="times"
                  onClick={() => act('eject')}
                />
              </>
            }>
            <LabeledList>
              {data.missing_organs !== 'nothing' ? (
                <MissingOrgans />
              ) : (
                <BlockQuote>No organs missing.</BlockQuote>
              )}
            </LabeledList>
            <Section title="Internal Organ Status">
              {data.has_internal_injuries ? (
                <OrganWindow />
              ) : (
                <BlockQuote color="good">
                  No internal injuries detected.
                </BlockQuote>
              )}
            </Section>
            <Section title="External Organ Status">
              {data.has_external_injuries ? (
                <ExternalOrganWindow />
              ) : (
                <BlockQuote color="good">
                  No external injuries detected.
                </BlockQuote>
              )}
            </Section>
          </Section>
        </Table.Cell>
      </Table.Row>
    </Table>
  );
};

export const OrganWindow = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <Table>
      <Table.Row color="blue">
        <Table.Cell>Name</Table.Cell>
        <Table.Cell>Trauma</Table.Cell>
        <Table.Cell>Wounds</Table.Cell>
        <Table.Cell>Location</Table.Cell>
      </Table.Row>
      {data.organs.map((organ) => (
        <Table.Row key={organ.name}>
          <Table.Cell>{organ.name}</Table.Cell>
          <Table.Cell color={damageLabel(organ.damage)}>
            {organ.damage}
          </Table.Cell>
          <Table.Cell>{organ.wounds}</Table.Cell>
          <Table.Cell>{organ.location}</Table.Cell>
        </Table.Row>
      ))}
    </Table>
  );
};

export const ExternalOrganWindow = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <Table>
      <Table.Row color="blue">
        <Table.Cell>Name</Table.Cell>
        <Table.Cell>Brute</Table.Cell>
        <Table.Cell>Burn</Table.Cell>
        <Table.Cell>Wounds</Table.Cell>
      </Table.Row>
      {data.bodyparts.map((organ) => (
        <Table.Row key={organ.name}>
          <Table.Cell>{organ.name}</Table.Cell>
          <Table.Cell color={damageLabel(organ.brute_damage)}>
            {organ.brute_damage}
          </Table.Cell>
          <Table.Cell color={damageLabel(organ.burn_damage)}>
            {organ.burn_damage}
          </Table.Cell>
          <Table.Cell>{organ.wounds}</Table.Cell>
        </Table.Row>
      ))}
    </Table>
  );
};

export const MissingOrgans = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return 'stuff';
};

export const TraumaInfo = (props, context) => {
  const { act, data } = useBackend<ScannerData>(context);

  return (
    <>
      <LabeledList.Item
        label="Physical Trauma"
        color={damageLabel(data.bruteLoss)}>
        {data.bruteLoss}
      </LabeledList.Item>
      <LabeledList.Item
        label="Oxygen Deprivation"
        color={damageLabel(data.oxyLoss)}>
        {data.oxyLoss}
      </LabeledList.Item>
      <LabeledList.Item label="Organ Failure" color={damageLabel(data.toxLoss)}>
        {data.toxLoss}
      </LabeledList.Item>
      <LabeledList.Item
        label="Burn Severity"
        color={damageLabel(data.fireLoss)}>
        {data.fireLoss}
      </LabeledList.Item>
    </>
  );
};

const consciousnessLabel = (value) => {
  switch (value) {
    case 0:
      return 'green';
    case 1:
      return 'average';
    case 2:
      return 'bad';
  }
};
const consciousnessText = (value) => {
  switch (value) {
    case 0:
      return 'Conscious';
    case 1:
      return 'Unconscious';
    case 2:
      return 'DEAD';
  }
};

const progressClass = (value) => {
  if (value <= 50) {
    return 'bad';
  } else if (value <= 90) {
    return 'average';
  } else {
    return 'green';
  }
};

const brainText = (value) => {
  switch (value) {
    case 0:
      return 'None, patient is braindead';
    case -1:
      return 'ERROR - Non-Standard Biology';
    default:
      return value.toString().concat('%');
  }
};

const damageLabel = (value) => {
  if (value === 'Fatal' || value < 10) {
    return 'bad';
  }
  if (value === 'Critical' || value < 20) {
    return 'bad';
  } else if (value === 'Severe' || value < 40) {
    return 'average';
  } else if (value === 'Significant' || value < 60) {
    return 'orange';
  } else if (value === 'Moderate' || value < 80) {
    return 'yellow';
  } else if (value === 'Minor' || value < 100) {
    return 'good';
  } else {
    return 'green';
  }
};

const getPressureClass = (tpressure) => {
  switch (tpressure) {
    case 1:
      return 'red';
    case 2:
      return 'green';
    case 3:
      return 'good';
    case 4:
      return 'red';
    default:
      return 'teal';
  }
};
