// vueui/src/components/view/vehicles/droppod.vue
<template>
  <div>
    <h2 class="white">Welcome, Operative.</h2>

    <h2>Please select your launch target:</h2>

    <div v-if="status == 0">
      <div>Pod status: <span class="good">Operational.</span></div>
      <div><vui-button icon="cog" :params="{ fire: 'recreational_areas'}">Recreational Areas</vui-button></div>
      <div><vui-button icon="cog" :params="{ fire: 'operations'}">Operations</vui-button></div>
      <div><vui-button icon="cog" :params="{ fire: 'starboard_wing'}">Starboard Wing Frame Interior</vui-button></div>
    </div>
    <div v-else>
      Pod status: <span class="bad">Non-operational.</span>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>

// tgui/packages/tgui/interfaces/DropPod.tsx
import { useBackend } from '../backend';
import { BlockQuote, Button, LabeledList, Section } from '../components';
import { Window } from '../layouts';

export type PodData = {
  status: number;
};

export const DropPod = (props) => {
  const { act, data } = useBackend<PodData>();

  return (
    <Window resizable theme="zavodskoi">
      <Window.Content scrollable>
        {data.status === 0 ? (
          <Section title="Select Launch Target">
            <BlockQuote>Drop pod operational.</BlockQuote>
            <LabeledList>
              <LabeledList.Item label="Recreational Areas">
                <Button
                  content="FIRE"
                  color="bad"
                  icon="radiation"
                  onClick={() => act('fire', { fire: 'recreational_areas' })}
                />
              </LabeledList.Item>
              <LabeledList.Item label="Operations">
                <Button
                  content="FIRE"
                  color="bad"
                  icon="radiation"
                  onClick={() => act('fire', { fire: 'operations' })}
                />
              </LabeledList.Item>
              <LabeledList.Item label="Starboard Wing Frame Interior">
                <Button
                  content="FIRE"
                  color="bad"
                  icon="radiation"
                  onClick={() => act('fire', { fire: 'starboard_wing' })}
                />
              </LabeledList.Item>
            </LabeledList>
          </Section>
        ) : (
          <BlockQuote>Drop pod not operational.</BlockQuote>
        )}
      </Window.Content>
    </Window>
  );
};
