// vueui/components/view/fax.vue
<template>
    <div>
        <div class="item">
            <div class="itemLabel">Confirm identity:</div>
            <div class="itemContent">
                <vui-button :params="{ scan: 1 }" icon="eject"><span v-if="state.idname">{{ state.idname }}</span><span v-else>--------</span></vui-button>
            </div>
        </div>
        <div v-if="state.auth" style="margin-top: 24px; clear: both;">
            <b>Logged in to:</b> {{ state.bossname }} Quantum Entanglement Network
            <template v-if="remaining_cooldown <= 0">
                <div class="item">
                    <div class="itemLabel">Sending to:</div>
                    <div class="itemContent">
                        <select v-model.lazy="state.destination" class="button">
                            <option v-for="dep in state.departiments" :key="dep" :value="dep">{{ dep }}</option>
                        </select>
                    </div>
                </div>
                <template v-if="state.paper">
                    <div class="item">
                        <div class="itemLabel">Currently sending:</div>
                        <div class="itemContent">
                            {{ state.paper }}
                        </div>
                    </div>
                    <div class="item">
                        <div class="itemLabel"></div>
                        <div class="itemContent">
                            <vui-button :params="{ send: 1}">Send</vui-button>
                        </div>
                    </div>
                </template>
                <span v-else>Please insert paper to send via secure connection.</span>
            </template>
            <span v-else><b>Transmitter arrays realigning. Please stand by. {{ remaining_cooldown | roundRemaining}} seconds remaining.</b></span>
        </div>
        <vui-button v-if="state.paper" :params="{ remove: 1}">Remove item</vui-button>
        
        <h3>PDAs to notify:</h3>
        <div v-for="pda in state.alertpdas" :key="pda.ref">
            {{ pda.name }} <vui-button :params="{ unlink: pda.ref }">Unlink</vui-button>
        </div>
        <div v-if="state.alertpdas.length <= 0">No PDAs are linked.</div>
        <vui-button :params="{ linkpda: 1 }">Add PDA to Notify</vui-button>
    </div>
</template>

<script>
export default {
    name: 'view-fax',
    data() {
        return this.$root.$data;
    },
    computed: {
        remaining_cooldown() {
            return this.state.cooldownend - this.wtime 
        }
    },
    filters: {
        roundRemaining(value) {
            return Math.round(value / 10);
        }
    }
};
</script>

<style lang="scss" scoped>
</style>

// tgui/packages/tgui/interfaces/Fax.tsx
import {
  BlockQuote,
  Box,
  Button,
  Dropdown,
  LabeledList,
  Section,
} from 'tgui-core/components';
import { round } from 'tgui-core/math';
import type { BooleanLike } from 'tgui-core/react';
import { capitalizeAll } from 'tgui-core/string';
import { useBackend } from '../backend';
import { Window } from '../layouts';

type PDA = {
  name: string;
  ref: string;
};

type FaxData = {
  destination: string;
  bossname: string;
  auth: BooleanLike;
  cooldown_end: number;
  idname: string;
  paper: string;
  world_time: number;
  alertpdas: PDA[];
  department: string;
  departments: string[];
};

export const Fax = (props) => {
  const { act, data } = useBackend<FaxData>();

  return (
    <Window>
      <Window.Content scrollable>
        <Section title="Confirm Identity">
          <Button
            content={data.idname ? data.idname : '-------'}
            icon="eject"
            onClick={(value) => act('remove_id')}
          />
        </Section>
        <Section title="Document">
          {data.paper ? (
            <PaperWindow />
          ) : (
            <Box>Please insert the document to send.</Box>
          )}
        </Section>
        {data.auth ? (
          <FaxWindow />
        ) : (
          <Section title="No identification provided." />
        )}
        <Section title="PDAs to Notify">
          {data.alertpdas.length ? (
            <PDANotifyWindow />
          ) : (
            <Box>No PDAs linked.</Box>
          )}
          <Button
            icon="plus"
            content="Link PDA"
            onClick={(value) => act('linkpda')}
          />
        </Section>
      </Window.Content>
    </Window>
  );
};

const FaxWindow = (props) => {
  const { act, data } = useBackend<FaxData>();
  const remaining_cooldown = data.cooldown_end - data.world_time;

  return (
    <Section title="Fax Options">
      <LabeledList>
        <LabeledList.Item label="Logged Into">
          {data.bossname} Bluespace Communication System{' '}
        </LabeledList.Item>
      </LabeledList>
      {remaining_cooldown <= 0 ? (
        <SendWindow />
      ) : (
        <Box>
          Transmitter arrays re-aligning. Please stand by.{' '}
          <Box>
            <b>{round(remaining_cooldown / 10, 0)}</b> seconds remaining.
          </Box>
        </Box>
      )}
    </Section>
  );
};

const SendWindow = (props) => {
  const { act, data } = useBackend<FaxData>();

  return (
    <Section>
      <LabeledList>
        <LabeledList.Item label="Sending To">
          <Dropdown
            options={data.departments}
            selected={data.destination}
            onSelected={(value) =>
              act('select_destination', { select_destination: value })
            }
            width="100%"
            displayText={data.destination}
          />
        </LabeledList.Item>
      </LabeledList>
    </Section>
  );
};
const PaperWindow = (props) => {
  const { act, data } = useBackend<FaxData>();

  return (
    <Section>
      <LabeledList>
        <LabeledList.Item label="Currently Sending">
          {capitalizeAll(data.paper)}
        </LabeledList.Item>
      </LabeledList>
      {data.auth ? (
        <Button icon="copy" content="Send" onClick={(value) => act('send')} />
      ) : (
        ''
      )}
      <Button icon="stop" content="Remove" onClick={(value) => act('remove')} />
    </Section>
  );
};

const PDANotifyWindow = (props) => {
  const { act, data } = useBackend<FaxData>();

  return (
    <Section>
      {data.alertpdas.map((PDA) => (
        <Section key="PDA">
          <BlockQuote>
            {PDA.name}{' '}
            <Button
              icon="minus"
              content="Unlink"
              onClick={(value) => act('unlink', { unlink: PDA.ref })}
            />
          </BlockQuote>
        </Section>
      ))}
    </Section>
  );
};
