// vueui/src/components/view/security/guntracker.vue
<template>
  <div>
    <h3>Firearm Control System</h3>
    <h3>Detected Firearms</h3>
    <table>
      <tr>
        <th>User</th>
        <th>Firearm</th>
        <th/>
      </tr>
      <tr v-for="gun in wireless_firing_pins" :key="gun.ref">
        <td>{{ gun.registered_info }}</td>
        <td>{{ gun.gun_name }}</td>
        <td>
          <vui-button :class="{'button' : 1, 'selected' : gun.disabled_state}" :params="{ pin: gun.ref, action: 'setdisable' }">Disabled</vui-button>
          <vui-button :class="{'button' : 1, 'selected' : gun.automatic_state}" :params="{ pin: gun.ref, action: 'setauto' }">Automatic</vui-button>
          <vui-button :class="{'button' : 1, 'selected' : gun.stun_state}" :params="{ pin: gun.ref, action: 'setstun' }">Stun Only</vui-button>
          <vui-button :class="{'button' : 1, 'selected' : gun.lethal_state}" :params="{ pin: gun.ref, action: 'setlethal' }">Unrestricted</vui-button>
        </td>
      </tr>
    </table>
  </div>
</template>



<script>
export default {
		data() {return this.$root.$data.state},

};
</script>

<style lang="scss" scoped>
table {
    width: 100%;
    text-align: center;
  }
</style>

// tgui/packages/tgui/interfaces/GunTracker.tsx
import { useBackend } from '../backend';
import { Button, Section, Table } from '../components';
import { NtosWindow } from '../layouts';

export type TrackerData = {
  wireless_firing_pins: Pin[];
};

type Pin = {
  gun_name: string;
  registered_info: string;
  ref: string;
  lock_status: number; // 1 disabled, 2 auto, 3 stun, 4 lethal
};

export const GunTracker = (props) => {
  const { act, data } = useBackend<TrackerData>();

  return (
    <NtosWindow resizable width={800}>
      <NtosWindow.Content scrollable>
        <Section title="Detected Firearms">
          <Table>
            <Table.Row header>
              <Table.Cell>User</Table.Cell>
              <Table.Cell>Firearm</Table.Cell>
              <Table.Cell>Setting</Table.Cell>
            </Table.Row>
            {data.wireless_firing_pins.map((pin) => (
              <Table.Row key={pin.ref}>
                <Table.Cell>{pin.registered_info}</Table.Cell>
                <Table.Cell>{pin.gun_name}</Table.Cell>
                <Table.Cell>
                  <Button
                    content="Disabled"
                    selected={pin.lock_status === 1}
                    onClick={() => act('set_disable', { pin: pin.ref })}
                  />
                  <Button
                    content="Automatic"
                    selected={pin.lock_status === 2}
                    onClick={() => act('set_auto', { pin: pin.ref })}
                  />
                  <Button
                    content="Stun Only"
                    selected={pin.lock_status === 3}
                    onClick={() => act('set_stun', { pin: pin.ref })}
                  />
                  <Button
                    content="Unrestricted"
                    selected={pin.lock_status === 4}
                    onClick={() => act('set_lethal', { pin: pin.ref })}
                  />
                </Table.Cell>
              </Table.Row>
            ))}
          </Table>
        </Section>
      </NtosWindow.Content>
    </NtosWindow>
  );
};
