// vueui/src/components/view/mcomputer/security/implanttracker.vue
<template>
  <div>
    <h3>Chemical Implants</h3>
    <table class="table border">
      <tr class="header border">
        <th>Implanted User</th>
        <th>Remaining Chemical Units</th>
        <th>Options</th>
      </tr>
      <tr v-for="chem in chem_implants" class="item border" :key="chem.ref">
        <td>{{ chem.implanted_name }}</td>
        <td>{{ chem.remaining_units }}</td>
        <td>
          <vui-button :params="{ inject1: chem.ref }">Inject 1u</vui-button>
          <vui-button :params="{ inject5: chem.ref }">Inject 5u</vui-button>
          <vui-button :params="{ inject5: chem.ref }">Inject 10u</vui-button>
        </td>
      </tr>
    </table>
    <h3>Tracking Implants</h3>
    <table class="table border">
      <tr class="header border">
        <th>Tracking ID</th>
        <th>Current Area</th>
        <th>Options</th>
      </tr>
      <tr v-for="tracker in tracking_implants" class="item border" :key="tracker.ref">
        <td>{{ tracker.id }}</td>
        <td>{{ tracker.loc_display }}</td>
        <td>
          <vui-button :params="{ warn: tracker.ref }">Message Implanted User</vui-button>
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>

<style lang="scss" scoped>
table {
  width: 100%;
  text-align: center;
}
tr {
  line-height: 135%;
}
</style>

// tgui/packages/tgui/interfaces/ImplantTracker.tsx
import { useBackend } from '../backend';
import { Button, Section, Table } from 'tgui-core/components';
import { NtosWindow } from '../layouts';

export type TrackerData = {
  chem_implants: ChemImplant[];
  tracking_implants: TrackingImplant[];
};

type ChemImplant = {
  implanted_name: string;
  remaining_units: number;
  ref: string;
};

type TrackingImplant = {
  id: number;
  loc_display: string;
  ref: string;
};

export const ImplantTracker = (props) => {
  const { act, data } = useBackend<TrackerData>();

  return (
    <NtosWindow width={800}>
      <NtosWindow.Content scrollable>
        <Section title="Chemical Implants">
          <Table>
            <Table.Row header>
              <Table.Cell>Implanted User</Table.Cell>
              <Table.Cell>Remaining Chemical Units</Table.Cell>
              <Table.Cell>Options</Table.Cell>
            </Table.Row>
            {data.chem_implants.map((chemimplant) => (
              <Table.Row key={chemimplant.ref}>
                <Table.Cell>{chemimplant.implanted_name}</Table.Cell>
                <Table.Cell>{chemimplant.remaining_units}u</Table.Cell>
                <Table.Cell>
                  <Button
                    content="Inject 1u"
                    icon="tint"
                    onClick={() => act('inject1', { inject1: chemimplant.ref })}
                  />
                  <Button
                    content="Inject 5u"
                    icon="tint"
                    onClick={() => act('inject5', { inject5: chemimplant.ref })}
                  />
                  <Button
                    content="Inject 10u"
                    icon="tint"
                    onClick={() =>
                      act('inject10', { inject10: chemimplant.ref })
                    }
                  />
                </Table.Cell>
              </Table.Row>
            ))}
          </Table>
        </Section>
        <Section title="Tracking Implants">
          <Table>
            <Table.Row header>
              <Table.Cell>Tracking ID</Table.Cell>
              <Table.Cell>Current Area</Table.Cell>
              <Table.Cell>Options</Table.Cell>
            </Table.Row>
            {data.tracking_implants.map((trackingimplant) => (
              <Table.Row key={trackingimplant.ref}>
                <Table.Cell>{trackingimplant.id}</Table.Cell>
                <Table.Cell>{trackingimplant.loc_display}</Table.Cell>
                <Table.Cell>
                  <Button
                    content="Message Implanted User"
                    icon="exclamation"
                    onClick={() => act('warn', { warn: trackingimplant.ref })}
                  />
                </Table.Cell>
              </Table.Row>
            ))}
          </Table>
        </Section>
      </NtosWindow.Content>
    </NtosWindow>
  );
};
