// vueui/src/components/view/devices/assembly/infrared.vue
<template>
  <div>
    <div>
      <h3>Status:</h3>
      <vui-button v-if="active" :params="{ state: 1 }">Active</vui-button>
      <vui-button v-else :params="{ state: 1 }">Inactive</vui-button>
    </div>
    <div>
      <h3>Beam Visibility:</h3>
      <vui-button v-if="visible" :params="{ visible: 1 }">Visible</vui-button>
      <vui-button v-else :params="{ visible: 1 }">Invisible</vui-button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state
  },
}
</script>

// tgui/packages/tgui/interfaces/Infrared.tsx
import type { BooleanLike } from 'tgui-core/react';
import { useBackend } from '../backend';
import { Button } from 'tgui-core/components';
import { Window } from '../layouts';

export type InfraredData = {
  active: BooleanLike;
  visible: BooleanLike;
};

export const Infrared = (props) => {
  const { act, data } = useBackend<InfraredData>();

  return (
    <Window>
      <Window.Content scrollable>
        <Button
          content={data.active ? 'Active' : 'Inactive'}
          checked={data.active}
          onClick={() => act('state')}
        />
        <Button.Checkbox
          content={data.visible ? 'Visible' : 'Invisible'}
          checked={data.visible}
          onClick={() => act('visible')}
        />
      </Window.Content>
    </Window>
  );
};
