// vueui/src/components/view/vehicles/pussywagon.vue
<template>
  <div>
    <h2>TRUCK STATUS</h2>
    <div v-if="is_on">
      The engine is currently running. <vui-button :params="{ toggle_engine: 1}">Stop</vui-button>
    </div>
    <div v-else>
      The engine is off. <vui-button :disabled="!has_key || !has_cell" :params="{ toggle_engine: 1}">Start</vui-button>
    </div>
    <div v-if="has_key">
      There is a key inserted into the ignition. <vui-button :params="{ key: 1}">Remove Key</vui-button>
    </div>
    <div v-else>
      There is no key in the ignition.
    </div>
    <div v-if="has_cell">
      Cell Charge: <vui-progress :class="{ good: cell_charge >= cell_max_charge * 0.8, bad: cell_charge <= cell_max_charge * 0.4, average: cell_charge < cell_max_charge * 0.8 && cell_charge > cell_max_charge * 0.4 }" :value="cell_charge" :max="cell_max_charge" :min="0">{{ cell_charge }}J</vui-progress> <vui-tooltip label="?">The cell can be removed by using a screwdriver to open the maintenance panel, then using a crowbar to shimmy it out.</vui-tooltip>
    </div>
    <div v-else>
      There is no cell installed. <vui-tooltip label="?">The cell can be installed by using a screwdriver to open the maintenance panel, then clicking on the engine with a compatible power cell.</vui-tooltip>
    </div>
    <div v-if="is_towing">
      This engine is currently towing the {{ tow }}. <vui-button :params="{ unlatch: 1}">Unlatch</vui-button>
      <div>
        <h2>TROLLEY STATUS</h2>
      </div>
      <div v-if="has_proper_trolley">
        <div v-if="is_hoovering">
          The trolley is currently vacuuming. <vui-button :params="{ toggle_hoover: 1}">Toggle</vui-button>
        </div>
        <div v-else>
          The trolley is not vacuuming. <vui-button :disabled="!is_on" :params="{ toggle_hoover: 1}">Toggle</vui-button>
        </div>
        <div>
          Vacuum Capacity Remaining: <vui-progress :class="{ good: vacuum_capacity >= max_vacuum_capacity * 0.8, bad: vacuum_capacity <= max_vacuum_capacity * 0.4, average: vacuum_capacity < max_vacuum_capacity * 0.8 && vacuum_capacity > max_vacuum_capacity * 0.4 }" :value="vacuum_capacity" :max="max_vacuum_capacity" :min="0">{{ vacuum_capacity }} L</vui-progress> <vui-button :disabled="vacuum_capacity >= max_vacuum_capacity" :params="{ empty_hoover: 1}">Empty</vui-button>
        </div>
        <div v-if="is_mopping">
          The trolley is currently mopping. <vui-button :disabled="!is_on || !has_bucket || bucket_capacity <= 0" :params="{ toggle_mop: 1}">Toggle</vui-button>
        </div>
        <div v-else>
          The trolley is not mopping. <vui-button :disabled="!is_on || !has_bucket" :params="{ toggle_mop: 1}">Toggle</vui-button>
        </div>
        <div v-if="has_bucket">
          The trolley has a reagent container installed. <vui-tooltip label="?">The trolley must have a reagent container installed to draw reagents from, such as water or space cleaner. This can be done by opening the maintenance panel on the trolley with a screwdriver and clicking on it with a bucket. Similarly, with an open panel, it can be removed by using a wrench on it.</vui-tooltip>
          <div>
            Container Reagents Remaining: <vui-progress :class="{ good: bucket_capacity >= max_bucket_capacity * 0.8, bad: bucket_capacity <= max_bucket_capacity * 0.4, average: bucket_capacity < max_bucket_capacity * 0.8 && bucket_capacity > max_bucket_capacity * 0.4 }" :value="bucket_capacity" :max="max_bucket_capacity" :min="0">{{ bucket_capacity }} cl</vui-progress>
          </div>
        </div>
        <div v-else>
          The trolley does not have a reagent container installed. <vui-tooltip label="?">The trolley must have a reagent container installed to draw reagents from, such as water or space cleaner. This can be done by opening the maintenance panel on the trolley with a screwdriver and clicking on it with a bucket. Similarly, with an open panel, it can be removed by using a wrench on it.</vui-tooltip>
        </div>
      </div>
      <div v-else>
        The wagon does not have the correct trolley installed.
      </div>
    </div>
    <div v-else>
      This engine isn't towing anything currently. <vui-tooltip label="?">You can latch vehicles together by dragging from the vehicle you want to be the anchor point, to the trolley you wish to latch.</vui-tooltip>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>

// tgui/packages/tgui/interfaces/PussyWagon.tsx
import { BooleanLike } from '../../common/react';
import { useBackend } from '../backend';
import { Button, LabeledList, ProgressBar, Section } from '../components';
import { Window } from '../layouts';

export type WagonData = {
  // Base cargo train data
  is_on: BooleanLike;
  has_key: BooleanLike;
  has_cell: BooleanLike;
  cell_charge: number;
  tow: string;

  // Janicart data
  has_proper_trolley: BooleanLike;
  is_hoovering: BooleanLike;
  vacuum_capacity: number;
  max_vacuum_capacity: number;
  is_mopping: BooleanLike;
  has_bucket: BooleanLike;
  bucket_capacity: number;
  max_bucket_capacity: number;
};

export const PussyWagon = (props) => {
  const { act, data } = useBackend<WagonData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Status">
          <LabeledList>
            <LabeledList.Item label="Engine">
              <Button
                content={data.is_on ? 'Running' : 'Stopped'}
                icon={data.is_on ? 'power-off' : 'times'}
                color={data.is_on ? 'good' : 'bad'}
                onClick={() => act('toggle_engine')}
              />
            </LabeledList.Item>
            <LabeledList.Item label="Key">
              <Button
                content={data.has_key ? 'Remove' : 'Not Inserted'}
                disabled={!data.has_key}
                icon="key"
                onClick={() => act('key')}
              />
            </LabeledList.Item>
            <LabeledList.Item label="Cell">
              {data.has_cell ? (
                <ProgressBar
                  ranges={{
                    good: [75, 100],
                    average: [30, 75],
                    bad: [0, 30],
                  }}
                  value={data.cell_charge}
                  minValue={0}
                  maxValue={100}>
                  {Math.round(data.cell_charge)}%
                </ProgressBar>
              ) : (
                'Not Inserted'
              )}
            </LabeledList.Item>
            <LabeledList.Item label="Towing">
              {data.tow ? (
                <Button
                  content={data.tow}
                  icon="times"
                  onClick={() => act('unlatch')}
                />
              ) : (
                'Nothing'
              )}
            </LabeledList.Item>
          </LabeledList>
          <Section title="Controls">
            {data.has_proper_trolley ? (
              <ControlsWindow />
            ) : (
              'Unrecognised trolley.'
            )}
          </Section>
        </Section>
      </Window.Content>
    </Window>
  );
};

export const ControlsWindow = (props) => {
  const { act, data } = useBackend<WagonData>();

  return (
    <LabeledList>
      <LabeledList.Item label="Vacuum">
        <Button
          content={data.is_hoovering ? 'Active' : 'Inactive'}
          icon={data.is_hoovering ? 'power-off' : 'times'}
          onClick={() => act('toggle_hoover')}
        />
      </LabeledList.Item>
      <LabeledList.Item label="Vacuum Capacity">
        <ProgressBar
          ranges={{
            good: [data.max_vacuum_capacity * 0.8, data.max_vacuum_capacity],
            average: [
              data.max_vacuum_capacity * 0.4,
              data.max_vacuum_capacity * 0.8,
            ],
            bad: [0, data.max_vacuum_capacity * 0.4],
          }}
          value={data.vacuum_capacity}
          minValue={0}
          maxValue={data.max_vacuum_capacity}>
          {data.vacuum_capacity} L
        </ProgressBar>
      </LabeledList.Item>
      <LabeledList.Item label="Mopping">
        <Button
          content={data.is_mopping ? 'Active' : 'Inactive'}
          disabled={
            !data.is_on || !data.has_bucket || data.bucket_capacity <= 0
          }
          icon={data.is_mopping ? 'power-off' : 'times'}
          onClick={() => act('toggle_mop')}
        />
      </LabeledList.Item>
      <LabeledList.Item label="Container Reagents Remaining">
        {data.has_bucket ? (
          <ProgressBar
            ranges={{
              good: [data.max_bucket_capacity * 0.8, data.max_bucket_capacity],
              average: [
                data.max_bucket_capacity * 0.4,
                data.max_bucket_capacity * 0.8,
              ],
              bad: [0, data.max_bucket_capacity * 0.4],
            }}
            value={data.bucket_capacity}
            minValue={0}
            maxValue={data.max_bucket_capacity}>
            {data.bucket_capacity} cl
          </ProgressBar>
        ) : (
          'No Container'
        )}
      </LabeledList.Item>
    </LabeledList>
  );
};
