// vueui/src/components/view/shuttles/shuttle-control-console-multi.vue
<template>
  <div>
    <h3>Shuttle Status</h3>
    <vui-group>
      <vui-group-item label="Status:">{{ shuttle_status }}</vui-group-item>
      <vui-group-item label="Engines:">{{ engine_status }}</vui-group-item>
      <vui-group-item v-if="has_docking" label="Docking:">{{ docking_status }}</vui-group-item>
    </vui-group>
    <h3>Shuttle Control</h3>
    <vui-item label="Current Destination:">
      <select v-model="$root.$data.state.current_destination" class="button">
        <option v-for="des in destinations" :key="des" :value="des">{{ des }}</option>
      </select>
      <vui-button :params="{ set_destination: 1 }">Lock Destination</vui-button>
    </vui-item>
    <vui-button :disabled="!can_launch" :params="{ move: 1 }">Launch Shuttle</vui-button>
    <vui-button :disabled="!can_cancel" :params="{ cancel: 1 }">Cancel Launch</vui-button>
    <vui-button class="red" :disabled="!can_force" :params="{ force: 1 }">Force Launch</vui-button>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
}
</script>

// tgui/packages/tgui/interfaces/ShuttleControlConsoleMulti.tsx
import { useBackend } from '../backend';
import { Button, Section, Box, LabeledList } from '../components';
import { Window } from '../layouts';

export type ShuttleControlConsoleMultiData = {
  shuttle_status: string;
  shuttle_state: string;
  has_docking: boolean;
  docking_status: string;
  docking_override: boolean;
  can_launch: boolean;
  can_cancel: boolean;
  can_force: boolean;
  can_rename_ship: boolean;
  can_pick: boolean;
  ship_name: string;
  destination_name: string;
};

export const ShuttleControlConsoleMulti = (props) => {
  const { act, data } = useBackend<ShuttleControlConsoleMultiData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Shuttle Status">
          <Box pb={2}>{data.shuttle_status}</Box>
          <Box pb={1}>Ship designation and name: {data.ship_name}</Box>
          {data.can_rename_ship ? (
            <Box pb={2}>
              <Button
                content="Rename"
                icon="pen"
                onClick={() => act('rename')}
              />
            </Box>
          ) : null}
          <Box>
            <LabeledList>
              <LabeledList.Item label="Drive">
                {data.shuttle_state === 'idle'
                  ? 'Idle'
                  : data.shuttle_state === 'warmup'
                    ? 'Spinning up'
                    : data.shuttle_state === 'in_transit'
                      ? 'Engaged'
                      : 'Error'}
              </LabeledList.Item>
              {data.has_docking ? (
                <LabeledList.Item label="Docking Status">
                  {data.docking_status === 'docked'
                    ? 'Docked'
                    : data.docking_status === 'docking'
                      ? data.docking_override
                        ? 'Docking-Manual'
                        : 'Docking'
                      : data.docking_status === 'undocking'
                        ? data.docking_override
                          ? 'Undocking-Manual'
                          : 'Undocking'
                        : data.docking_status === 'undocked'
                          ? 'Undocked'
                          : 'Error'}
                </LabeledList.Item>
              ) : null}
            </LabeledList>
          </Box>
        </Section>
        <Section title="Destination Control">
          <Box pb={1}>
            <LabeledList>
              <LabeledList.Item label="Current Destination">
                {data.destination_name}
              </LabeledList.Item>
            </LabeledList>
          </Box>
          <Button
            content="Choose Destination"
            icon="plane-arrival"
            disabled={!data.can_pick}
            onClick={() => act('pick')}
          />
        </Section>
        <Section title="Shuttle Control">
          <Button
            content="Launch Shuttle"
            icon="rocket"
            disabled={!data.can_launch}
            onClick={() => act('move')}
          />
          <Button
            content="Cancel Launch"
            icon="ban"
            disabled={!data.can_cancel}
            onClick={() => act('cancel')}
          />
          <Button
            content="Force Launch"
            icon="triangle-exclamation"
            color="red"
            disabled={!data.can_force}
            onClick={() => act('force')}
          />
        </Section>
      </Window.Content>
    </Window>
  );
};
