// vueui/src/components/view/medical/sleeper.vue
<template>
  <div>
    <div v-if="!power">
      <div class="itemLabel">
        <h2>NO POWER</h2>
      </div>
    </div>
    <div v-else>
      <div v-if="occupant">
        <div class="columnHolder">
          <div class="column">
            <div>
              <h3>Occupant Status:</h3>
              <div><span class="text">Status:</span> <span :style="{color:consciousnessLabel(stat)}">{{ consciousnessText(stat) }}</span></div>
              <div><span class="text">Stasis Level:</span> {{stasis}}</div>
              <div><span class="text">Species:</span> {{species}}</div>
              <div><span class="text">Brain Activity:</span> <vui-progress :class="progressClass(brain_activity)" :value="brain_activity">{{brain_activity}}%</vui-progress></div>
              <div><span class="text">Pulse:</span> {{pulse}}</div>
              <div><span class="text">BP:</span> <span :style="{color:getPressureClass(blood_pressure_level)}">{{blood_pressure}}</span></div>
              <div><span class="text">Blood Oxygenation:</span> <vui-progress :class="progressClass(brain_activity)" :value="Math.round(blood_o2)">{{Math.round(blood_o2)}}%</vui-progress></div>
              <h3>Bloodstream Reagents:</h3>
              <div v-if="bloodreagents">
                <table>
                  <tr v-for="reagent in bloodreagents" :key="reagent.name">
                    <td><span class="text">{{reagent.name}}:</span></td>
                    <td class="shifted">{{reagent.amount}}u</td>
                  </tr>
                </table>
              </div>
              <div v-else>
                The occupant has no additional reagents in their bloodstream.
              </div>
              <h3>Stomach Reagents:</h3>
              <div v-if="hasstomach">
                <div v-if="stomachreagents">
                  <table>
                    <tr v-for="reagent in stomachreagents" :key="reagent.name">
                      <td><span class="text">{{reagent.name}}:</span></td>
                      <td class="shifted">{{reagent.amount}}u</td>
                    </tr>
                  </table>
                </div>
                <div v-else>
                  The occupant has nothing in their stomach.
                </div>
              </div>
              <div v-else>
                The occupant does not have a stomach.
              </div>
            </div>
          </div>
          <div class="column">
            <h3>Injectable Reagents:</h3>
            <table>
              <tr v-for="reagent in reagents" :key="reagent.name">
                <td><span class="text">{{reagent.name}}:</span></td>
                <td><vui-button :params="{chemical: reagent.type, amount: 5}">Inject 5</vui-button></td>
                <td><vui-button :params="{chemical: reagent.type, amount: 10}">Inject 10</vui-button></td>
              </tr>
            </table>
            <h3>Stasis Settings:</h3>
            <table>
              <tr>
                <td v-for="setting in stasissettings" :key="setting">
                  <vui-button :params="{stasis: setting}">{{setting}}</vui-button>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <div v-else>
        No occupant.
      </div>
    </div>
    <div v-if="occupant">
      <div class="columnHolder">
        <div class="float">
          <vui-button :params="{eject: 1}">Eject Occupant</vui-button>
        </div>
        <div class="float">
          <div v-if="filtering">
            <vui-button :params="{filter: -1}">Dialysis Active</vui-button>
          </div>
          <div v-else>
            <vui-button :params="{filter: 1}">Dialysis Inactive</vui-button>
          </div>
        </div>
        <div class="float">
          <div v-if="pump">
            <vui-button :params="{pump: -1}">Stomach Pump Active</vui-button>
          </div>
          <div v-else>
            <vui-button :params="{pump: 1}">Stomach Pump Inactive</vui-button>
          </div>
        </div>
      </div>
    </div>
    <div v-if="beaker != -1">
      <span class="text">Beaker:</span> {{beaker}} units of free space remaining. <vui-button :params="{beaker: 1}">Eject Beaker</vui-button>
    </div>
    <div v-else>
      No beaker inserted.
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  },
  methods: {
  consciousnessLabel(value) {
    switch (value) {
      case 0:
        return "LimeGreen"
      case 1:
        return "OrangeRed"
      case 2:
        return "Crimson"
      }
    },
  consciousnessText(value) {
  switch (value) {
    case 0:
      return "Conscious"
    case 1:
      return "Unconscious"
    case 2:
      return "DEAD"
    }
  },
  progressClass(value) {
    if (value <= 50) {
      return "bad"
    }
    else if (value <= 90) {
      return "average"
    }
    else {
      return "good"
    }
  },
  getPressureClass(tpressure) {
    switch (tpressure) {
      case 1:
        return "Crimson"
      case 2:
        return "LimeGreen"
      case 3:
        return "LawnGreen"
      case 4:
        return "Crimson"
      default:
        return "LightSkyBlue"
      }
    }
  }
};
</script>

<style lang="scss" scoped>
.column {
    float: left;
    width: 45%;
    margin: 1%;
    padding: 10px;
    outline-style: ridge;
    outline-color: black;
    background-color: rgba(0, 0, 0, 0.4);
    height: 500px;
    overflow: auto;
}
/* Clear floats after the columns */
.columnHolder:after {
    content:"";
    display: block;
    height: 0;
    overflow: hidden;
    clear: both;
}
.text {
  color: #b99d71;
}
.float .button {
  float: left;
  padding-left: 5px;
}
td .shifted {
  padding-left: 5px;
}
</style>

// tgui/packages/tgui/interfaces/Sleeper.tsx
import type { BooleanLike } from 'tgui-core/react';
import { useBackend } from '../backend';
import { BlockQuote, Button, Knob, LabeledList, ProgressBar, Section, Table } from 'tgui-core/components';
import { Window } from '../layouts';

export type SleeperData = {
  occupant: BooleanLike;
  stat: number;
  stasis: number;
  species: string;
  brain_activity: number;
  blood_pressure: number[];
  blood_pressure_level: number;
  blood_o2: number;
  bloodreagents: Reagent[];
  hasstomach: BooleanLike;
  stomachreagents: Reagent[];
  pulse: string;
  reagents: SleeperReagent[];
  stasissettings: number[];
  beaker: BooleanLike;
  beakerfreespace: number;
  filtering: BooleanLike;
  pump: BooleanLike;
};

type Reagent = {
  name: string;
  amount: number;
};

type SleeperReagent = {
  type: string;
  name: string;
};

export const Sleeper = (props) => {
  const { act, data } = useBackend<SleeperData>();

  return (
    <Window theme="zenghu">
      <Window.Content scrollable>
        {data.occupant ? (
          <OccupantStatus />
        ) : (
          <Table>
            <BlockQuote>No occupant detected.</BlockQuote>
            <Button
              content={data.beaker ? 'Eject Beaker' : 'No Beaker'}
              icon="medkit"
              color="red"
              disabled={!data.beaker}
              onClick={() => act('beaker')}
            />
          </Table>
        )}
      </Window.Content>
    </Window>
  );
};

export const OccupantStatus = (props) => {
  const { act, data } = useBackend<SleeperData>();

  return (
    <Table>
      <Table.Row header>
        <Table.Cell>
          <Section
            title="Occupant Status"
            buttons={
              <Button
                content="Eject Occupant"
                color="bad"
                icon="person-booth"
                onClick={() => act('eject')}
              />
            }>
            <LabeledList>
              <LabeledList.Item
                label="Status"
                color={consciousnessLabel(data.stat)}>
                {consciousnessText(data.stat)}
              </LabeledList.Item>
              <LabeledList.Item label="Stasis Level">
                {data.stasis}x
              </LabeledList.Item>
              <LabeledList.Item label="Species">
                {data.species}
              </LabeledList.Item>
              <LabeledList.Item label="Brain Activity">
                <ProgressBar
                  ranges={{
                    good: [85, 100],
                    average: [40, 85],
                    bad: [0, 40],
                  }}
                  value={data.brain_activity}
                  minValue={0}
                  maxValue={100}>
                  {data.brain_activity}%
                </ProgressBar>
              </LabeledList.Item>
              <LabeledList.Item
                label="Pulse"
                color={progressClass(data.brain_activity)}>
                {data.pulse}
              </LabeledList.Item>
              <LabeledList.Item
                label="BP"
                color={getPressureClass(data.blood_pressure_level)}>
                {data.blood_pressure}
              </LabeledList.Item>
              <LabeledList.Item
                label="Blood Oxygenation"
                color={progressClass(data.blood_o2)}>
                {Math.round(data.blood_o2)}
              </LabeledList.Item>
            </LabeledList>
          </Section>
          <Section title="Bloodstream Reagents">
            {data.bloodreagents.length ? (
              <BloodReagents />
            ) : (
              'No detected reagents in the bloodstream.'
            )}
          </Section>
          <Section title="Stomach Reagents">
            {data.hasstomach ? (
              data.stomachreagents.length ? (
                <StomachReagents />
              ) : (
                'No detected reagents in the stomach.'
              )
            ) : (
              'No stomach detected.'
            )}
          </Section>
          <Section title="Injectable Reagents">
            <Table>
              {data.reagents.map((reagent) => (
                <Table.Row key={reagent.name}>
                  <Table.Cell>{reagent.name}</Table.Cell>
                  <Table.Cell>
                    <Button
                      content="Inject 5"
                      onClick={() =>
                        act('chemical', { chemical: reagent.type, amount: 5 })
                      }
                    />
                  </Table.Cell>
                  <Table.Cell>
                    <Button
                      content="Inject 10"
                      onClick={() =>
                        act('chemical', { chemical: reagent.type, amount: 10 })
                      }
                    />
                  </Table.Cell>
                </Table.Row>
              ))}
            </Table>
            <Section title="Stasis">
              <Knob
                size={1.25}
                value={data.stasis}
                unit="x"
                minValue={data.stasissettings[0]}
                maxValue={data.stasissettings[data.stasissettings.length - 1]}
                step={1}
                stepPixelSize={50}
                onDrag={(e, value) =>
                  act('stasis', {
                    stasis: value,
                  })
                }
              />
            </Section>
            <Section
              title="Dialysis"
              buttons={
                <Button
                  content={data.beaker ? 'Eject Beaker' : 'No Beaker'}
                  icon="medkit"
                  color="red"
                  disabled={!data.beaker}
                  onClick={() => act('beaker')}
                />
              }>
              <Button
                content="Blood Dialysis"
                color={data.filtering ? 'good' : ''}
                disabled={!data.beaker || data.beakerfreespace <= 0}
                icon="heart"
                onClick={() => act('filter')}
              />
              <Button
                content="Stomach Pump"
                color={data.pump ? 'good' : ''}
                disabled={!data.beaker || data.beakerfreespace <= 0}
                icon="splotch"
                onClick={() => act('pump')}
              />
              {data.beaker ? (
                <BlockQuote>
                  {Math.round(data.beakerfreespace)}u of free space remaining.
                </BlockQuote>
              ) : (
                <BlockQuote color="bad">No beaker inserted.</BlockQuote>
              )}
            </Section>
          </Section>
        </Table.Cell>
      </Table.Row>
    </Table>
  );
};

export const BloodReagents = (props) => {
  const { act, data } = useBackend<SleeperData>();

  return (
    <Table>
      {data.bloodreagents.map((reagent) => (
        <Table.Row key={reagent.name}>
          <Table.Cell>{reagent.name}</Table.Cell>
          <Table.Cell>{reagent.amount}u</Table.Cell>
        </Table.Row>
      ))}
    </Table>
  );
};

// is this shit copypaste? yeah i dont care, you try converting 75 UIs over 2 months
export const StomachReagents = (props) => {
  const { act, data } = useBackend<SleeperData>();

  return (
    <Table>
      {data.stomachreagents.map((reagent) => (
        <>
          <Table.Row key={reagent.name}>{reagent.name}</Table.Row>
          <Table.Row key={reagent.amount}>{reagent.amount}u</Table.Row>
        </>
      ))}
    </Table>
  );
};

const consciousnessLabel = (value) => {
  switch (value) {
    case 0:
      return 'green';
    case 1:
      return 'average';
    case 2:
      return 'bad';
  }
};
const consciousnessText = (value) => {
  switch (value) {
    case 0:
      return 'Conscious';
    case 1:
      return 'Unconscious';
    case 2:
      return 'DEAD';
  }
};

const progressClass = (value) => {
  if (value <= 50) {
    return 'bad';
  } else if (value <= 90) {
    return 'average';
  } else {
    return 'green';
  }
};

const getPressureClass = (tpressure) => {
  switch (tpressure) {
    case 1:
      return 'red';
    case 2:
      return 'green';
    case 3:
      return 'good';
    case 4:
      return 'red';
    default:
      return 'teal';
  }
};
