// vueui/src/components/view/devices/vitalsmonitor.vue
<template>
  <div>
    <h3>Patient Vitals:</h3>
    <template v-if="has_occupant">
      <vui-group>
        <vui-group-item label="Status:"><span :style="{color:consciousnessLabel(stat)}">{{ consciousnessText(stat) }}</span></vui-group-item>
        <vui-group-item label="Brain Activity:"><vui-progress :class="progressClass(brain_activity)" :value="brain_activity">{{brain_activity}}%</vui-progress></vui-group-item>
        <vui-group-item label="BP:" :style="{color:getPressureClass(blood_pressure_level)}">{{blood_pressure}}</vui-group-item>
        <vui-group-item label="Blood Oxygenation:"><vui-progress :class="progressClass(brain_activity)" :value="Math.round(blood_o2)">{{Math.round(blood_o2)}}%</vui-progress></vui-group-item>
        <vui-group-item label="Blood Volume:"><vui-progress :class="progressClass(brain_activity)" :value="Math.round(blood_volume)">{{Math.round(blood_volume)}}%</vui-progress></vui-group-item>
      </vui-group>
    </template>
    <template v-else>
      <span class="bad">No patient detected.</span>
    </template>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  },
  methods: {
    consciousnessLabel(value) {
      switch (value) {
        case 0:
          return "LimeGreen"
        case 1:
          return "OrangeRed"
        case 2:
          return "Crimson"
      }
    },
    consciousnessText(value) {
      switch (value) {
        case 0:
          return "Conscious"
        case 1:
          return "Unconscious"
        case 2:
          return "DEAD"
      }
    },
    progressClass(value) {
      if (value <= 50) {
        return "bad"
      }
      else if (value <= 90) {
        return "average"
      }
      else {
        return "good"
      }
    },
    getPressureClass(tpressure) {
      switch (tpressure) {
        case 1:
          return "Crimson"
        case 2:
          return "LimeGreen"
        case 3:
          return "LawnGreen"
        case 4:
          return "Crimson"
        default:
          return "LightSkyBlue"
      }
    }
  }
};
</script>

// tgui/packages/tgui/interfaces/VitalsMonitor.tsx
import { BooleanLike } from 'common/react';
import { useBackend } from '../backend';
import { Section, Box, LabeledList } from '../components';
import { Window } from '../layouts';

export type VitalsData = {
  has_occupant: BooleanLike;
  stat: number;
  brain_activity: number;
  blood_pressure: number;
  blood_pressure_level: number;
  blood_volume: number;
  blood_o2: number;
};

export const VitalsMonitor = (props) => {
  const { act, data } = useBackend<VitalsData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Patient Vitals">
          {data.has_occupant ? (
            <PatientVitals />
          ) : (
            <Box bold>No patient detected.</Box>
          )}
        </Section>
      </Window.Content>
    </Window>
  );
};

const PatientVitals = (props) => {
  const { act, data } = useBackend<VitalsData>();
  return (
    <Section>
      <LabeledList>
        <LabeledList.Item label="Status" color={ConsciousnessLabel(data.stat)}>
          {ConsciousnessText(data.stat)}
        </LabeledList.Item>
        <LabeledList.Item
          label="Brain Activity"
          color={ProgressClass(data.brain_activity)}>
          {data.brain_activity}%
        </LabeledList.Item>
        <LabeledList.Item
          label="BP"
          color={PressureClass(data.blood_pressure_level)}>
          {data.blood_pressure}
        </LabeledList.Item>
        <LabeledList.Item
          label="Blood Oxygenation"
          color={ProgressClass(Math.round(data.blood_o2))}>
          {Math.round(data.blood_o2)}%
        </LabeledList.Item>
        <LabeledList.Item
          label="Blood Volume"
          color={ProgressClass(Math.round(data.blood_volume))}>
          {Math.round(data.blood_volume)}%
        </LabeledList.Item>
      </LabeledList>
    </Section>
  );
};

const ConsciousnessLabel = (value) => {
  switch (value) {
    case 0:
      return 'good';
    case 1:
      return 'average';
    case 2:
      return 'bad';
  }
};

const ConsciousnessText = (value) => {
  switch (value) {
    case 0:
      return 'Conscious';
    case 1:
      return 'Unconscious';
    case 2:
      return 'DEAD';
  }
};

const ProgressClass = (value) => {
  if (value <= 50) {
    return 'bad';
  } else if (value <= 90) {
    return 'average';
  } else {
    return 'good';
  }
};

const PressureClass = (value) => {
  switch (value) {
    case 1:
      return 'bad';
    case 2:
      return 'green';
    case 3:
      return 'good';
    case 4:
      return 'bad';
    default:
      return 'teal';
  }
};
