// vueui/src/components/view/misc/voting.vue
<template>
  <div>
    <template v-if="mode">
      <h2>Vote: {{question}}</h2>
      Time Left: {{reman}} s<hr>
      <table>
        <tr>
          <th>Choices</th><th>Votes</th><th v-if="mode == 'gamemode'">Minimum Players</th>
        </tr>
        <tr v-for="(options, choice) in uichoices" :key="choice">
          <td><vui-button :class="{on: choice == voted}" style="text-align:left;" :params="{action: 'vote', vote: choice}">{{options.name}}</vui-button></td><td>{{options.votes}}</td><td v-if="options.extra">{{options.extra}}</td>
        </tr>
      </table>
      <hr>
      <template v-if="isstaff">
        <vui-button :params="{action: 'cancel'}">Cancel</vui-button>
      </template>
    </template>
    <template v-else>
      <h2>Start a vote:</h2>
      <hr>
      <ul>
        <li>
          <vui-button :disabled="!isstaff && !allow_vote_restart" :params="{action: 'restart'}">Restart</vui-button>
        </li>
        <li>
          <vui-button :disabled="!isstaff && !allow_vote_restart" :params="{action: 'crew_transfer'}">Crew Transfer</vui-button>
          <span v-if="(isstaff || allow_vote_restart) && is_code_red">(Disallowed, Code Red or above)</span>
          <vui-button :class="{on: allow_vote_restart}" v-if="isstaff" :params="{action: 'toggle_restart'}">Toggle Restart / Crew Transfer voting</vui-button>
        </li>
        <li>
          <vui-button :disabled="!isstaff && !allow_vote_mode" :params="{action: 'gamemode'}">GameMode</vui-button>
          <vui-button :class="{on: allow_vote_mode}" v-if="isstaff" :params="{action: 'toggle_gamemode'}">Toggle GameMode voting</vui-button>
        </li>
        <li>
          <vui-button :disabled="!allow_extra_antags" :params="{action: 'add_antagonist'}">Add Antagonist Type</vui-button>
        </li>
        <li>
          <vui-button :disabled="!isstaff" :params="{action: 'custom'}">Custom</vui-button>
        </li>
      </ul>
    </template>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  },
  computed: {
    uichoices() {
      if(typeof this.choices === 'object') {
        return this.choices
      } else {
        return {}
      }
    },
    reman() {
      return Math.round((this.endtime - this.$root.$data.wtime) / 10)
    }
  }
}
</script>

<style lang="scss" scoped>
  table {
    width: 100%;
    th {
      font-weight: bold;
    }
    th, td {
      text-align: center;
    }
  }
</style>

// tgui/packages/tgui/interfaces/Voting.tsx
import { useBackend } from '../backend';
import { capitalizeAll } from '../../common/string';
import { Window } from '../layouts';
import { Section, Button, Box, Table } from '../components';

type VoteChoice = {
  choice: string;
  votes: number;
  extra: string;
};

export type VotingData = {
  choices: VoteChoice[];
  is_staff: boolean;
  mode: string;
  question: string;
  voted: string;
  allow_vote_restart: boolean;
  allow_vote_mode: boolean;
  allow_extra_antags: boolean;
};

export const Voting = (props, context) => {
  const { act, data } = useBackend<VotingData>(context);

  return (
    <Window resizable>
      <Window.Content scrollable>
        {data.mode ? <VoteWindow /> : <StartVoteWindow />}
      </Window.Content>
    </Window>
  );
};

export const VoteWindow = (props, context) => {
  const { act, data } = useBackend<VotingData>(context);
  return (
    <Section collapsing title={data.question}>
      <Table>
        <Table.Row header>
          <Table.Cell>
            <Box bold>Choices</Box>
          </Table.Cell>
          <Table.Cell textAlign="right">
            <Box bold>Votes</Box>
          </Table.Cell>
          {data.mode === 'gamemode' && (
            <Table.Cell textAlign="center">Minimum Players</Table.Cell>
          )}
        </Table.Row>
        {data.choices.map((choice) => (
          <Table.Row key={choice.choice}>
            <Table.Cell>
              <Button
                content={capitalizeAll(choice.choice)}
                selected={choice.choice === data.voted}
                onClick={(value) => act('vote', { vote: choice })}
              />
            </Table.Cell>
            <Table.Cell textAlign="center">{choice.votes}</Table.Cell>
            {data.mode === 'gamemode' && (
              <Table.Cell textAlign="center">{choice.extra}</Table.Cell>
            )}
          </Table.Row>
        ))}
      </Table>
    </Section>
  );
};

export const StartVoteWindow = (props, context) => {
  const { act, data } = useBackend<VotingData>(context);
  return (
    <Section collapsing title="Start a Vote">
      <Box>
        <Button
          content="Restart"
          disabled={!data.allow_vote_restart}
          onClick={(value) => act('restart')}
        />
      </Box>
      <Box>
        <Button
          content="Crew Transfer"
          disabled={!data.allow_vote_restart}
          tooltip="Disallowed on Code Red or above."
          onClick={(value) => act('crew_transfer')}
        />
      </Box>
      <Box>
        <Button
          content="Toggle Restart / Crew Transfer Voting"
          disabled={!data.is_staff}
          onClick={(value) => act('toggle_restart')}
        />
      </Box>
      <Box>
        <Button
          content="Toggle Gamemode Voting"
          disabled={!data.is_staff || !data.allow_vote_mode}
          onClick={(value) => act('toggle_gamemode')}
        />
      </Box>
      <Box>
        <Button
          content="Add Antagonist Type"
          disabled={!data.allow_extra_antags}
          onClick={(value) => act('add_antagonist')}
        />
      </Box>
      <Box>
        <Button
          content="Custom"
          disabled={!data.is_staff}
          onClick={(value) => act('custom')}
        />
      </Box>
    </Section>
  );
};
