// tgui/packages/tgui/interfaces/AICard.tsx
import type { BooleanLike } from 'tgui-core/react';
import { useBackend } from '../backend';
import { LabeledList, Section, Table, Button } from 'tgui-core/components';
import { Window } from '../layouts';

export type AIData = {
  has_ai: BooleanLike;
  name: string;
  hardware_integrity: number;
  backup_capacitor: number;
  radio: BooleanLike;
  wireless: BooleanLike;
  operational: BooleanLike;
  flushing: BooleanLike;
  laws: Law[];
  has_laws: BooleanLike;
};

type Law = {
  index: number;
  law: string;
};

export const AICard = (props) => {
  const { act, data } = useBackend<AIData>();

  return (
    <Window>
      <Window.Content scrollable>
        <Section title="AI Status">
          {data.has_ai ? <AIWindow /> : <b>No AI detected.</b>}
        </Section>
      </Window.Content>
    </Window>
  );
};

export const AIWindow = (props) => {
  const { act, data } = useBackend<AIData>();

  return (
    <>
      <Section>
        <LabeledList>
          <LabeledList.Item label="Hardware Integrity">
            {data.hardware_integrity}%
          </LabeledList.Item>
          <LabeledList.Item label="Backup Capacitor">
            {data.backup_capacitor}%
          </LabeledList.Item>
        </LabeledList>
      </Section>
      <Section title="Laws">
        {data.has_laws ? <LawWindow /> : <b>No laws detected.</b>}
      </Section>
      <CommandWindow />
    </>
  );
};

export const LawWindow = (props) => {
  const { act, data } = useBackend<AIData>();
  const { laws } = data;

  return (
    <Table>
      <Table.Row header>
        <Table.Cell>Index</Table.Cell>
        <Table.Cell>Law</Table.Cell>
      </Table.Row>
      {laws.map((law) => (
        <Table.Row key={law.law}>
          <Table.Cell>{law.index}</Table.Cell>
          <Table.Cell>{law.law}</Table.Cell>
        </Table.Row>
      ))}
    </Table>
  );
};

export const CommandWindow = (props) => {
  const { act, data } = useBackend<AIData>();
  const { laws } = data;

  return (
    <Section title="Commands">
      <LabeledList>
        <LabeledList.Item label="Radio Subspace Transmission">
          <Button
            content={data.radio ? 'Enabled' : 'Disabled'}
            icon="info"
            color={data.radio ? 'good' : 'danger'}
            onClick={() => act('radio', { radio: data.radio ? 1 : 0 })}
          />
        </LabeledList.Item>
        <LabeledList.Item label="Wireless Interface">
          <Button
            content={data.wireless ? 'Enabled' : 'Disabled'}
            icon="wifi"
            color={data.wireless ? 'good' : 'danger'}
            onClick={() => act('wireless', { wireless: data.wireless ? 1 : 0 })}
          />
        </LabeledList.Item>
        <LabeledList.Item label="Wipe AI">
          <Button
            content={data.flushing ? 'WIPING...' : 'Wipe'}
            icon="exclamation"
            color={data.flushing ? 'danger' : 'orange'}
            disabled={data.flushing}
            onClick={() => act('wipe')}
          />
        </LabeledList.Item>
      </LabeledList>
    </Section>
  );
};

// vueui/src/components/view/devices/aicard.vue
<template>
  <div>
    <template v-if="has_ai">
      <vui-group>
        <vui-group-item label="Hardware Integrity">{{ hardware_integrity }}%</vui-group-item>
        <vui-group-item label="Backup Capacitor">{{ backup_capacitor }}%</vui-group-item>
      </vui-group>

      <table v-if="has_laws" class="borders">
        <tr>
          <td class="law_index">Index</td>
          <td>Law</td>
        </tr>

        <div class="itemLabelNarrow">
          Laws:
        </div>
        <tr v-for="law in laws" :key="law.index">
          <td valign="top">{{ law.index }}</td>
          <td>{{ law.law }}</td>
        </tr>
      </table>

      <span class="notice" v-else>
        No laws found.
      </span>

      <vui-group v-if="operational">
        <vui-group-item label="Radio Subspace Transceiver">
          <vui-button :class="{ selected: radio }" :params="{ radio: 0 }">Enabled</vui-button>
          <vui-button :class="{ danger: !radio }" :params="{ radio: 1 }">Disabled</vui-button>
        </vui-group-item>

        <vui-group-item label="Wireless Interface">
          <vui-button :class="{ selected: wireless }" :params="{ wireless: 0 }">Enabled</vui-button>
          <vui-button :class="{ danger: !wireless }" :params="{ wireless: 1 }">Disabled</vui-button>
        </vui-group-item>

        <vui-group-item v-if="flushing">
          <span class="notice">AI wipe in progress...</span>
        </vui-group-item>
        <vui-group-item v-else label="Wipe AI">
          <vui-button class="danger" :params="{ wipe: 1 }">Wipe</vui-button>
        </vui-group-item>
      </vui-group>
    </template>
    <template v-else> Stored AI: <span class="notice">No AI detected.</span> </template>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state
  },
}
</script>
