// tgui/packages/tgui/interfaces/Jammer.tsx
import { useBackend } from '../backend';
import { Button, LabeledList, Section } from '../components';
import { Window } from '../layouts';

export type JammerData = {
  active: number;
};

export const Jammer = (props) => {
  const { act, data } = useBackend<JammerData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Jammer Level">
          <LabeledList>
            <LabeledList.Item label="Block Nothing">
              <Button
                content={data.active === -1 ? 'On' : 'Off'}
                icon="power-off"
                onClick={() => act('set_active', { set_active: -1 })}
                color={data.active === -1 ? 'bad' : ''}
              />
            </LabeledList.Item>
            <LabeledList.Item label="Block Synthetics">
              <Button
                content={data.active === 2 ? 'On' : 'Off'}
                icon="power-off"
                onClick={() => act('set_active', { set_active: 2 })}
                color={data.active === 2 ? 'good' : ''}
              />
            </LabeledList.Item>
            <LabeledList.Item label="Block All">
              <Button
                content={data.active === 1 ? 'On' : 'Off'}
                icon="power-off"
                onClick={() => act('set_active', { set_active: 1 })}
                color={data.active === 1 ? 'good' : ''}
              />
            </LabeledList.Item>
          </LabeledList>
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/devices/jammer.vue
<template>
  <div>
    <h3>Jammer Level:</h3>
    <div>
      <vui-button :class="{selected: active == 1}" :params="{ set_active: 1 }">Block All</vui-button>
    </div>
    <div>
      <vui-button :class="{selected: active == 2}" :params="{ set_active: 2 }">Block Synthetics</vui-button>
    </div>
    <div>
      <vui-button :class="{selected: active == -1}" :params="{ set_active: -1 }">Block Nothing</vui-button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>
