// vueui/src/components/view/manifest.vue
<template>
  <div>
    <div v-if="manifestLen(fixedmanifest) > 0">
      <table v-for="(el, dept) in fixedmanifest" :key="dept" class="mt-2" :class="'border-dept-' + dept.toLowerCase()">
        <tr :class="'bg-dept-' + dept.toLowerCase()">
          <th colspan="3" class="fw-bold">{{ dept }}</th>
        </tr>
        <tr v-for="entry in el" :key="entry.name" :class="{fwBold: entry.head}">
          <td class="pl-2">{{ entry.name }}</td>
          <td class="px-1">{{ entry.rank }}</td>
          <td class="pr-2 text-right">{{ entry.active }}</td>
        </tr>
      </table>
    </div>
    <div v-else class="fst-italic">
      There is no crew.
    </div>
    <div v-if="allow_printing" class="text-center mt-2">
      <vui-button :params="{ action: 'print' }" icon="print">Print current manifest</vui-button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    let ret = this.$root.$data.state
    ret.manifestLen = function(manif) {
      let len = 0
      Object.values(manif).forEach((val) => len += val.length)
      return len
    }
    return ret
  },
  computed: {
    fixedmanifest() {
      return Object.fromEntries(Object.entries(this.manifest).filter(([, crew]) => Object.entries(crew).length > 0))
    },
  },
}
</script>

<style lang="scss" scoped>
table {
  width: 100%;
  border-collapse: collapse;
  color: white;
  background-color: rgba(0, 0, 0, 0.6);
  border: 2px solid;
}
</style>

// tgui/packages/tgui/interfaces/common/Manifest.tsx
import { BooleanLike } from '../../../common/react';
import { useBackend } from '../../backend';
import { Button, Icon, Section, Table, Tooltip } from '../../components';
import { TableCell, TableRow } from '../../components/Table';

type ManifestData = {
  manifest: { department: Crew[] };
  allow_follow: BooleanLike;
};

type Crew = {
  name: string;
  rank: string;
  active: string;
  head: BooleanLike;
};

export const Manifest = (props, context) => {
  const { act, data } = useBackend<ManifestData>(context);
  const manifest = data.manifest || {};
  const allow_follow = data.allow_follow;
  return (
    <Section>
      {Object.keys(manifest).length === 0 && 'There are no crew active.'}
      {Object.keys(manifest).map((dept) => {
        const deptCrew = manifest[dept];
        return (
          <Section
            key={dept}
            title={dept}
            textAlign="center"
            className={'border-dept-' + dept.toLowerCase()}>
            <Table>
              {deptCrew.map((crewmate) => {
                return (
                  <TableRow key={crewmate.name} bold={crewmate.head}>
                    <TableCell width="50%" overflow="hidden">
                      {crewmate.name}
                    </TableCell>
                    <TableCell width="50%" overflow="hidden">
                      {crewmate.rank}
                    </TableCell>
                    <TableCell textAlign="right">
                      <Tooltip content={crewmate.active}>
                        <Icon
                          name="circle"
                          className={
                            'manifest-indicator-' +
                            crewmate.active.toLowerCase()
                          }
                        />
                      </Tooltip>
                    </TableCell>
                    {allow_follow ? (
                      <TableCell textAlign="right">
                        <Tooltip content="Follow mob">
                          <Button
                            content="F"
                            onClick={() =>
                              act('follow', { name: crewmate.name })
                            }
                          />
                        </Tooltip>
                      </TableCell>
                    ) : (
                      ''
                    )}
                  </TableRow>
                );
              })}
            </Table>
          </Section>
        );
      })}
    </Section>
  );
};
