// tgui/packages/tgui/interfaces/SmartFridge.tsx
import type { BooleanLike } from 'tgui-core/react';
import { useBackend, useLocalState } from '../backend';
import { BlockQuote, Box, Button, LabeledList, Section, Input } from 'tgui-core/components';
import { Window } from '../layouts';

export type FridgeData = {
  contents: Item[];
  seconds_electrified: BooleanLike;
  shoot_inventory: BooleanLike;
  locked: number; // goes to -1
  secure: BooleanLike;
  sort_alphabetically: BooleanLike;
};

type Item = {
  display_name: string;
  vend: number;
  quantity: number;
};

export const SmartFridge = (props) => {
  const { act, data } = useBackend<FridgeData>();
  const [searchTerm, setSearchTerm] = useLocalState<string>(
    `searchTerm`,
    ``
  );

  return (
    <Window>
      <Window.Content scrollable>
        <Section
          title="Storage"
          buttons={
            <Section>
              <Input
                selfClear
                placeholder="Search..."
                onInput={(e, value) => {
                  setSearchTerm(value);
                }}
                value={searchTerm}
              />
              <Button
                content="Sort"
                selected={data.sort_alphabetically}
                onClick={() => act('switch_sort_alphabetically')}
              />
            </Section>
          }>
          {data.secure ? (
            data.locked === -1 ? (
              <BlockQuote>
                <Box color="bad">
                  Sec.re ACC_** //:securi_ntdiag##or 1%($...
                </Box>
              </BlockQuote>
            ) : (
              <BlockQuote>
                <Box color="good">
                  Secure Access: Please have your identification ready.
                </Box>
              </BlockQuote>
            )
          ) : (
            ''
          )}
          {data.contents ? <ContentsWindow /> : 'No contents loaded.'}
        </Section>
      </Window.Content>
    </Window>
  );
};

export const ContentsWindow = (props) => {
  const { act, data } = useBackend<FridgeData>();
  const [searchTerm] = useLocalState<string>(`searchTerm`, ``);
  const itemList = data.contents.filter(
    (item) =>
      item.display_name.toLowerCase().indexOf(searchTerm.toLowerCase()) > -1
  );
  const itemListSorted = data.sort_alphabetically
    ? itemList.sort((item1, item2) => {
      return item1.display_name.localeCompare(item2.display_name);
    })
    : itemList;

  return (
    <Section>
      <LabeledList>
        {itemListSorted.map((item) => (
          <LabeledList.Item key={item.display_name} label={item.display_name}>
            x{item.quantity}&nbsp;
            {item.quantity > 0 ? (
              <Button
                content="x1"
                icon="arrow-alt-circle-down"
                onClick={() => {
                  act('vendItem', { vendItem: item.vend, amount: 1 });
                }}
              />
            ) : (
              ''
            )}
            {item.quantity > 5 ? (
              <Button
                content="x5"
                icon="arrow-alt-circle-down"
                onClick={() => {
                  act('vendItem', { vendItem: item.vend, amount: 5 });
                }}
              />
            ) : (
              ''
            )}
            {item.quantity > 10 ? (
              <Button
                content="x10"
                icon="arrow-alt-circle-down"
                onClick={() => {
                  act('vendItem', { vendItem: item.vend, amount: 10 });
                }}
              />
            ) : (
              ''
            )}
            {item.quantity > 25 ? (
              <Button
                content="x25"
                icon="arrow-alt-circle-down"
                onClick={() => {
                  act('vendItem', { vendItem: item.vend, amount: 25 });
                }}
              />
            ) : (
              ''
            )}
          </LabeledList.Item>
        ))}
      </LabeledList>
    </Section>
  );
};

// vueui/src/components/view/machinery/smartfridge.vue
<template>
  <div>
    <div>
      <vui-button icon="cog" class="fixedLeft" :params="{ close: 1 }">Close</vui-button>
    </div>

    <div>
      <h2>Storage</h2>
      <span v-if="secure" class="notice">
        {{ locked == -1 ? "Sec.re ACC_** //):securi_nt.diag=>##'or 1=1'%($..." : "Secure Access: Please have your identification ready." }}
      </span>
    </div>

    <template v-if="contents">
      <div v-for="vend_item in contents" :key="vend_item.vend">
        <div><span class="highlight">{{ vend_item.display_name }} ({{ vend_item.quantity }} available)</span></div>
        <div style="float: left;">Vend:&nbsp;</div>
        <vui-button :params="{ vendItem: vend_item.vend, amount: 1 }"
                    class="statusValue"
                    icon="arrow-alt-circle-down">x1</vui-button>
        <vui-button v-if="vend_item.quantity >= 5"
                    :params="{ vendItem: vend_item.vend, amount: 5 }"
                    class="statusValue"
                    icon="arrow-alt-circle-down">x5</vui-button>
        <vui-button v-if="vend_item.quantity >= 10"
                    :params="{ vendItem: vend_item.vend, amount: 10 }"
                    class="statusValue"
                    icon="arrow-alt-circle-down">x10</vui-button>
        <vui-button v-if="vend_item.quantity >= 25"
                    :params="{ vendItem: vend_item.vend, amount: 25 }"
                    class="statusValue"
                    icon="arrow-alt-circle-down">x25</vui-button>
        <vui-button v-if="vend_item.quantity > 1"
                    :params="{ vendItem: vend_item.vend, amount: vend_item.quantity }"
                    class="statusValue"
                    icon="arrow-alt-circle-down">All</vui-button>
      </div>
    </template>
    <div v-else class="average">
      No products loaded.
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>
