// tgui/packages/tgui/interfaces/Teleporter.tsx
import { BooleanLike } from 'tgui-core/react';
import { useBackend } from '../backend';
import { Button, LabeledList, Section, Table } from 'tgui-core/components';
import { NtosWindow } from '../layouts';

export type TeleporterData = {
  has_linked_pad: BooleanLike;
  nearby_pads: Pad[];
  selected_target: string; // ref
  selected_target_name: string;
  calibration: number;

  teleport_beacons: Beacon[];
  teleport_implants: Implant[];
};

type Pad = {
  name: string;
  ref: string;
};

type Beacon = {
  name: string;
  ref: string;
};

type Implant = {
  name: string;
  ref: string;
};

export const Teleporter = (props) => {
  const { act, data } = useBackend<TeleporterData>();

  return (
    <NtosWindow>
      <NtosWindow.Content scrollable>
        {data.has_linked_pad ? <TeleporterPad /> : <FindPad />}
      </NtosWindow.Content>
    </NtosWindow>
  );
};

export const TeleporterPad = (props) => {
  const { act, data } = useBackend<TeleporterData>();

  return (
    <>
      <Section title="Linked Pad Info">
        <LabeledList>
          <LabeledList.Item label="Target">
            {data.selected_target ? data.selected_target_name : 'Not Locked In'}
          </LabeledList.Item>
          <LabeledList.Item label="Calibration">
            {data.calibration}% &nbsp;{' '}
            <Button content="Recalibrate" onClick={() => act('recalibrate')} />
          </LabeledList.Item>
        </LabeledList>
      </Section>
      <Section title="Teleporter Beacons">
        <Table>
          <Table.Row header>
            <Table.Cell>Name</Table.Cell>
            <Table.Cell>Action</Table.Cell>
          </Table.Row>
          {data.teleport_beacons.map((beacon) => (
            <Table.Row key={beacon.ref}>
              <Table.Cell>{beacon.name}</Table.Cell>
              <Table.Cell>
                <Button
                  content={
                    data.selected_target === beacon.ref ? 'Unset' : 'Lock On'
                  }
                  color={data.selected_target === beacon.ref ? 'danger' : ''}
                  onClick={() =>
                    act('beacon', { beacon: beacon.ref, name: beacon.name })
                  }
                />
              </Table.Cell>
            </Table.Row>
          ))}
        </Table>
      </Section>
      <Section title="Tracking Implants">
        <Table>
          <Table.Row header>
            <Table.Cell>Name</Table.Cell>
            <Table.Cell>Action</Table.Cell>
          </Table.Row>
          {data.teleport_implants.map((implant) => (
            <Table.Row key={implant.ref}>
              <Table.Cell>{implant.name}</Table.Cell>
              <Table.Cell>
                <Button
                  content={
                    data.selected_target === implant.ref ? 'Unset' : 'Lock On'
                  }
                  color={data.selected_target === implant.ref ? 'danger' : ''}
                  onClick={() =>
                    act('implant', { implant: implant.ref, name: implant.name })
                  }
                />
              </Table.Cell>
            </Table.Row>
          ))}
        </Table>
      </Section>
    </>
  );
};

export const FindPad = (props) => {
  const { act, data } = useBackend<TeleporterData>();

  return (
    <Section title="Nearby Teleporter Pads">
      <Table>
        <Table.Row header>
          <Table.Cell>Pad</Table.Cell>
          <Table.Cell>Action</Table.Cell>
        </Table.Row>
        {data.nearby_pads.map((pad) => (
          <Table.Row key={pad.ref}>
            <Table.Cell>{pad.name}</Table.Cell>
            <Table.Cell>
              <Button
                content="Link"
                onClick={() => act('pad', { pad: pad.ref })}
              />
            </Table.Cell>
          </Table.Row>
        ))}
      </Table>
    </Section>
  );
};

// vueui/src/components/view/machinery/teleporter.vue
<template>
  <div>
    <h3>Station Info</h3>
    <span :class="station_locked_in ? 'good' : 'bad'">{{ station_locked_in ? 'Locked In ' : 'Not Locked In ' }}</span><span :class="station_locked_in ? 'good' : 'bad'">({{ locked_in_name }})</span>
    <br><span>Calibration: {{calibration}}%</span> <vui-button :params="{ recalibrate: 1 }">Recalibrate</vui-button>
    <h3>Teleporter Beacons</h3>
    <table class="table border">
      <tr class="header border">
        <th>Beacon Name</th>
        <th>Action</th>
      </tr>
      <tr v-for="beacon in teleport_beacons" class="item border" :key="beacon.ref">
        <td>{{ beacon.beacon_name }}</td>
        <td>
          <vui-button :class="{ 'danger' : beacon.selected_beacon == true}" :params="{ beacon: beacon.ref, name: beacon.beacon_name }">{{beacon.selected_beacon == true ? "Unset" : "Lock On"}}</vui-button>
        </td>
      </tr>
    </table>
    <h3>Tracking Implants</h3>
    <table class="table border">
      <tr class="header border">
        <th>Implant Name</th>
        <th>Action</th>
      </tr>
      <tr v-for="implant in teleport_implants" class="item border" :key="implant.ref">
        <td>{{ implant.implant_name }}</td>
        <td>
          <vui-button :class="{ 'danger' : implant.selected_implant == true}" :params="{ implant: implant.ref, name: implant.implant_name }">{{implant.selected_implant == true ? "Unset" : "Lock On"}}</vui-button>
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
};
</script>

<style lang="scss" scoped>
table {
  width: 100%;
  text-align: center;
}
tr {
  line-height: 135%;
}
</style>
