// tgui/packages/tgui/interfaces/SMES.tsx
import { BooleanLike } from '../../common/react';
import { useBackend } from '../backend';
import { Box, BlockQuote, Button, LabeledList, Section, ProgressBar, NumberInput } from '../components';
import { Window } from '../layouts';

export type SMESData = {
  name_tag: string;
  charge_taken: number;
  charging: BooleanLike;
  charge_attempt: BooleanLike;
  charge_level: number;
  charge_max: number;
  output_load: number;
  outputting: BooleanLike;
  output_attempt: BooleanLike;
  output_level: number;
  output_max: number;
  time: number;
  wtime: number;
  charge_mode: number;
  stored_capacity: number;
  fail_time: number;
};

export const SMES = (props) => {
  const { act, data } = useBackend<SMESData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        {data.fail_time ? <FailWindow /> : <SMESWindow />}
      </Window.Content>
    </Window>
  );
};

export const FailWindow = (props) => {
  const { act, data } = useBackend<SMESData>();

  return (
    <Section
      title="SYSTEM FAILURE"
      buttons={
        <Button
          content="Reboot Now"
          icon="sync"
          color="bad"
          onClick={() => act('reboot')}
        />
      }>
      <Box>I/O regulator malfuction detected! Waiting for system reboot...</Box>
      <BlockQuote>Automatic reboot in {data.fail_time} seconds...</BlockQuote>
    </Section>
  );
};

export const SMESWindow = (props) => {
  const { act, data } = useBackend<SMESData>();

  return (
    <Section title="Supermagnetic Storage">
      <LabeledList>
        <LabeledList.Item label="Stored Capacity">
          <ProgressBar
            color={data.charging ? 'good' : 'average'}
            value={data.stored_capacity}
            minValue={0}
            maxValue={100}
          />
        </LabeledList.Item>
        <LabeledList.Item label="Charge Status">
          {data.charge_mode === 1
            ? `Charge will complete in ${time_remaining(
              data.time,
              data.wtime
            )}.`
            : data.charge_mode === 2
              ? 'Output and input balanced.'
              : `Charge will run out in ${time_remaining(
                data.time,
                data.wtime
              )}.`}
        </LabeledList.Item>
      </LabeledList>
      <Section title="Input Management">
        <LabeledList>
          <LabeledList.Item label="Charge Mode">
            <Button
              content={data.charge_attempt ? 'Auto' : 'Off'}
              color={data.charge_attempt ? 'good' : 'bad'}
              icon={data.charge_attempt ? 'sync' : 'times'}
              onClick={() => act('cmode')}
            />
            <Box as="span" color={charge_class(data.charge_mode)}>
              [{charge_status(data.charge_mode)}]
            </Box>
          </LabeledList.Item>
          <LabeledList.Item label="Input Level">
            <ProgressBar
              value={data.charge_level}
              minValue={0}
              maxValue={data.charge_max}
            />
            <NumberInput
              value={data.charge_level}
              minValue={0}
              maxValue={data.charge_max}
              unit="W"
              step={5000}
              onDrag={(e, value) => act('input', { input: value })}
            />
          </LabeledList.Item>
          <LabeledList.Item label="Input Load">
            <ProgressBar
              color={data.charge_taken < data.charge_level ? 'average' : 'good'}
              value={data.charge_taken}
              minValue={0}
              maxValue={data.charge_max}>
              {data.charge_taken} W
            </ProgressBar>
          </LabeledList.Item>
        </LabeledList>
      </Section>
      <Section title="Output Management">
        <LabeledList>
          <LabeledList.Item label="Output Status">
            <Button
              content={data.output_attempt ? 'Online' : 'Offline'}
              color={data.output_attempt ? 'good' : 'bad'}
              icon={data.output_attempt ? 'power-off' : 'times'}
              onClick={() => act('online')}
            />
            <Box as="span" color={output_class(data.outputting)}>
              [{output_status(data.outputting)}]
            </Box>
          </LabeledList.Item>
          <LabeledList.Item label="Output Level">
            <ProgressBar
              value={data.output_level}
              minValue={0}
              maxValue={data.output_max}
            />
            <NumberInput
              value={data.output_level}
              minValue={0}
              maxValue={data.output_max}
              unit="W"
              step={5000}
              onDrag={(e, value) => act('output', { output: value })}
            />
          </LabeledList.Item>
          <LabeledList.Item label="Output Load">
            <ProgressBar
              color={data.output_load < data.output_level ? 'average' : 'good'}
              value={data.output_load}
              minValue={0}
              maxValue={data.output_max}>
              {data.output_load} W
            </ProgressBar>
          </LabeledList.Item>
        </LabeledList>
      </Section>
    </Section>
  );
};

const time_remaining = (time, wtime) => {
  let timeleft = (time - wtime) / 10; // deciseconds
  let hours = Math.round(timeleft / 3600);
  let minutes = Math.round((timeleft % 3600) / 60);
  let seconds = Math.round(timeleft % 60);
  return [
    hours >= 1 && `${hours} hours`,
    minutes >= 1 && `${minutes} minutes`,
    seconds >= 1 && `${seconds} seconds`,
  ]
    .filter(Boolean)
    .join(', ');
};

const charge_class = (charge_mode) => {
  switch (charge_mode) {
    case 2:
      return 'good';
    case 1:
      return 'average';
    default:
      return 'bad';
  }
};

const charge_status = (charge_mode) => {
  switch (charge_mode) {
    case 2:
      return 'Charging';
    case 1:
      return 'Partially Charging';
    default:
      return 'Not Charging';
  }
};

const output_class = (value) => {
  switch (value) {
    case 2:
      return 'good';
    case 1:
      return 'average';
    default:
      return 'bad';
  }
};

const output_status = (value) => {
  switch (value) {
    case 2:
      return 'Outputting';
    case 1:
      return 'Disconnected or No Charge';
    default:
      return 'Not Outputting';
  }
};

// vueui/src/components/view/machinery/power/smes.vue
<template>
  <div>
    <div v-if="state.failTime" class="notice"> <!-- Failure - Disabled -->
      <h3 class="fw-bold">SYSTEM FAILURE</h3>
      <span class="fst-italic">I/O regulator malfuction detected! Waiting for system reboot...</span><br>
      Automatic reboot in {{state.failTime}} seconds...
      <vui-button icon="sync" :params="{reboot : 1}">Reboot Now</vui-button>
    </div>
    <vui-group v-else>
      <vui-group-item label="Stored Capacity:">
        <vui-progress :value="state.storedCapacity" :min="0" :max="100" :class="state.charging ? 'good' : 'average'"/>
        <div class="statusValue">
          {{Math.round(state.storedCapacity)}}%
        </div>
      </vui-group-item>

      <vui-group-item label="Charge status:">
        <div class="statusValue">
          <span v-if="state.chargeMode == 1">
            SMES will be fully charged in {{timeRemaining}}
          </span>
          <span v-else-if="state.chargeMode == 2">
            SMES input and output are equal
          </span>
          <span v-else>
            SMES will run out of charge in {{timeRemaining}}
          </span>
        </div>
      </vui-group-item>

      <h3>Input Management</h3>
      <vui-group-item label="Charge Mode:">
        <vui-button :icon="state.chargeAttempt ? 'sync' : 'times'" :params="{cmode : 1}">{{state.chargeAttempt ? 'Auto' : 'Off'}}</vui-button>
        &nbsp;
        [<span :class="chargeClass">{{chargeStatus}}</span>]
      </vui-group-item>

      <vui-group-item label="Input Level:">
        <vui-progress :value="chargeLevel" :min="0" :max="state.chargeMax"/>
        <div style="clear: both; padding-top: 4px; text-align:center;">
          <vui-input-numeric width="100px" v-model="chargeLevel" min-button max-button :button-count="0" :min="0" :max="state.chargeMax"></vui-input-numeric>
        </div>
      </vui-group-item>

      <vui-group-item label="Input Load:">
        <vui-progress :value="state.chargeTaken" :min="0" :max="state.chargeMax" :class="(state.chargeTaken < state.chargeLevel) ? 'average' : 'good'"/>
        <div class="statusValue">
          {{state.chargeTaken}} W
        </div>
      </vui-group-item>

      <h3>Output Management</h3>
      <vui-group-item label="Output Status:">
        <vui-button :icon="state.outputOnline ? 'power-off' : 'times'" :params="{online : 1}">{{state.outputOnline ? 'On' : 'Off'}}line</vui-button>
        &nbsp;
        [<span :class="outputClass">{{outputStatus}}</span>]
      </vui-group-item>

      <vui-group-item label="Output Level:">
        <vui-progress :value="outputLevel" :min="0" :max="state.outputMax"/>
        <div style="clear: both; padding-top: 4px; text-align: center;">
          <vui-input-numeric width="100px" v-model="outputLevel" min-button max-button :button-count="0" :min="0" :max="state.outputMax"></vui-input-numeric>
        </div>
      </vui-group-item>

      <vui-group-item label="Output Load:">
        <vui-progress :value="state.outputLoad" :min="0" :max="state.outputMax" :class="(state.outputLoad < state.outputLevel) ? 'good' : 'average'"/>
        <div class="statusValue">
          {{state.outputLoad}} W
        </div>
      </vui-group-item>
    </vui-group>
  </div>
</template>

<script>
export default {
  data() {
    return {
      state: this.$root.$data.state,

    }
  },
  computed: {
    chargeLevel: {
      get() {
        return this.state.chargeLevel
      },
      set(value) {
        this.state.chargeLevel = value
        this.$toTopic({input : value})
      }
    },
    outputLevel: {
      get() {
        return this.state.outputLevel
      },
      set(value) {
        this.state.outputLevel = value
        this.$toTopic({output : value})
      }
    },
    chargeClass() {
      switch(this.state.chargeMode){
        case 2: return 'good';
        case 1: return 'average';
        default: return 'bad';
      }
    },
    chargeStatus() {
      switch(this.state.chargeMode){
        case 2: return "Charging";
        case 1: return "Partially Charging";
        default: return "Not Charging";
      }
    },
    outputClass() {
      switch(this.state.outputting){
        case 2: return 'good';
        case 1: return 'average';
        default: return 'bad';
      }
    },
    outputStatus() {
      switch(this.state.outputting){
        case 2: return "Outputting";
        case 1: return "Disconnected or No Charge";
        default: return "Not Outputting";
      }
    },
    timeRemaining() {
      var timeleft = (this.state.time - this.$root.$data.wtime)/10 // deciseconds
      var hours = Math.round(timeleft / 3600)
      var minutes = Math.round(timeleft % 3600 / 60)
      var seconds = Math.round(timeleft % 60)
      return [hours >= 1 && `${hours} hours`, minutes >= 1 && `${minutes} minutes`, seconds >= 1 && `${seconds} seconds`].filter(Boolean).join(", ")
    }
  }
}
</script>
