// tgui/packages/tgui/interfaces/ShuttleControlConsoleLift.tsx
import { useBackend } from '../backend';
import { Button, Section, LabeledList } from '../components';
import { Window } from '../layouts';

export type ShuttleControlConsoleLiftData = {
  shuttle_status: string;
  shuttle_state: string;
  has_docking: boolean;
  docking_status: string;
  docking_override: boolean;
  can_launch: boolean;
  can_cancel: boolean;
  can_force: boolean;
  can_rename_ship: boolean;
  ship_name: string;
};

export const ShuttleControlConsoleLift = (props) => {
  const { act, data } = useBackend<ShuttleControlConsoleLiftData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Lift Status">
          <LabeledList>
            <LabeledList.Item label="Status">
              {data.shuttle_state === 'idle'
                ? 'Idle'
                : data.shuttle_state === 'warmup'
                  ? 'Spinning up'
                  : data.shuttle_state === 'in_transit'
                    ? 'Moving'
                    : 'Error'}
            </LabeledList.Item>
          </LabeledList>
        </Section>
        <Section title="Lift Controls">
          <Button
            content="Move Lift"
            icon="elevator"
            disabled={!data.can_launch}
            onClick={() => act('move')}
          />
          <Button
            content="Stop Lift"
            icon="ban"
            disabled={!data.can_cancel}
            onClick={() => act('cancel')}
          />
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/shuttles/shuttle-control-console-lift.vue
<template>
  <div>
    <h3>Lift Status</h3>
    <div class="docking_controls">
      <vui-item label="Status:">{{ engine_status }}</vui-item>
    </div>
    <h3>Lift Controls</h3>
    <vui-button :disabled="!can_launch" :params="{ move: 1 }">Move Lift</vui-button>
    <vui-button :disabled="!can_cancel" :params="{ cancel: 1 }">Stop Lift</vui-button>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
}
</script>
