// tgui/packages/tgui/interfaces/DamageMenu.tsx
import { Button, Section, Table } from 'tgui-core/components';
import type { BooleanLike } from 'tgui-core/react';
import { useBackend } from '../backend';
import { Window } from '../layouts';

export type DamageData = {
  limbs: Organ[];
  organs: Organ[];
};

type Organ = {
  name: string;
  present: BooleanLike;
};

export const DamageMenu = (props) => {
  const { act, data } = useBackend<DamageData>();

  return (
    <Window theme="admin">
      <Window.Content scrollable>
        <Section title="Limbs">
          <Table>
            <Table.Row header>
              <Table.Cell>Name</Table.Cell>
              <Table.Cell>Action</Table.Cell>
            </Table.Row>
            {data.limbs.map((limb) =>
              limb.present ? (
                <Table.Row key={limb.name}>
                  <Table.Cell key={limb.name}>{limb.name}</Table.Cell>
                  <Table.Cell>
                    <Button
                      content="Brute"
                      onClick={() =>
                        act('limb', { action: 'brute', name: limb.name })
                      }
                    />
                    <Button
                      content="Burn"
                      onClick={() =>
                        act('limb', { action: 'burn', name: limb.name })
                      }
                    />
                    <Button
                      content="Infection"
                      onClick={() =>
                        act('limb', { action: 'infection', name: limb.name })
                      }
                    />
                    <Button
                      content="Shatter"
                      onClick={() =>
                        act('limb', { action: 'shatter', name: limb.name })
                      }
                    />
                    <Button
                      content="Arterial"
                      onClick={() =>
                        act('limb', { action: 'arterial', name: limb.name })
                      }
                    />
                    <Button
                      content="Sever"
                      onClick={() =>
                        act('limb', { action: 'sever', name: limb.name })
                      }
                    />
                  </Table.Cell>
                </Table.Row>
              ) : (
                ''
              ),
            )}
          </Table>
        </Section>
        <Section title="Organs">
          <Table>
            <Table.Row header>
              <Table.Cell>Name</Table.Cell>
              <Table.Cell>Action</Table.Cell>
            </Table.Row>
            {data.organs.map((organ) =>
              organ.present ? (
                <Table.Row key={organ.name}>
                  <Table.Cell key={organ.name}>{organ.name}</Table.Cell>
                  <Table.Cell>
                    <Button
                      content="Damage"
                      onClick={() =>
                        act('organ', { action: 'damage', name: organ.name })
                      }
                    />
                    <Button
                      content="Infection"
                      onClick={() =>
                        act('organ', { action: 'infection', name: organ.name })
                      }
                    />
                    <Button
                      content="Bruise"
                      onClick={() =>
                        act('organ', { action: 'bruise', name: organ.name })
                      }
                    />
                    <Button
                      content="Break"
                      onClick={() =>
                        act('organ', { action: 'break', name: organ.name })
                      }
                    />
                    <Button
                      content="Remove"
                      onClick={() =>
                        act('organ', { action: 'remove', name: organ.name })
                      }
                    />
                  </Table.Cell>
                </Table.Row>
              ) : (
                ''
              ),
            )}
          </Table>
        </Section>
        <Section title="Miscellaneous">
          <Button
            content="Toggle Wind"
            color="red"
            icon="wind"
            onClick={() => act('misc', { action: 'wind' })}
          />
          <Button
            content="Gigashatter"
            color="red"
            icon="bone"
            onClick={() => act('misc', { action: 'gigashatter' })}
          />
          <Button
            content="Kill"
            color="red"
            icon="skull-crossbones"
            onClick={() => act('misc', { action: 'kill' })}
          />
          <Button
            content="Gib"
            color="red"
            icon="splotch"
            onClick={() => act('misc', { action: 'gib' })}
          />
          <Button
            content="Dust"
            color="red"
            icon="exclamation-triangle"
            onClick={() => act('misc', { action: 'dust' })}
          />
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/admin/damage-menu.vue
<template>
  <div>
    <div>
      <h3>Limbs</h3>
      <table class="table border">
        <tr class="header border">
          <th>Name</th>
          <th>Tools</th>
        </tr>
        <tr v-for="(limbexists, limbname) in limbs" class="item border" :key="limbname">
          <td style="width:20%">{{ limbname }}</td>
          <td>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'brute' }">Brute</vui-button>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'burn' }">Burn</vui-button>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'infection' }">Infection</vui-button>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'shatter' }">Shatter</vui-button>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'arterial' }">Arterial</vui-button>
            <vui-button :params="{ target: 'limb', name: limbname, action: 'sever' }">Sever</vui-button>
          </td>
        </tr>
      </table>
    </div>
    <div>
      <h3>Organs</h3>
      <table class="table border">
        <tr class="header border">
          <th>Name</th>
          <th>Tools</th>
        </tr>
        <tr v-for="(organexists, organname) in organs" class="item border" :key="organname">
          <td style="width:20%">{{ organname }}</td>
          <td>
            <vui-button :params="{ target: 'organ', name: organname, action: 'damage' }">Damage</vui-button>
            <vui-button :params="{ target: 'organ', name: organname, action: 'infection' }">Infection</vui-button>
            <vui-button :params="{ target: 'organ', name: organname, action: 'bruise' }">Bruise</vui-button>
            <vui-button :params="{ target: 'organ', name: organname, action: 'break' }">Break</vui-button>
            <vui-button :params="{ target: 'organ', name: organname, action: 'remove' }">Remove</vui-button>
          </td>
        </tr>
      </table>
    </div>
    <div>
      <h3>Miscellaneous</h3>
      <vui-button :params="{ target: 'misc', action: 'wind' }">Toggle Wind</vui-button>
      <vui-button :params="{ target: 'misc', action: 'gigashatter' }">Gigashatter</vui-button>
      <vui-button :params="{ target: 'misc', action: 'kill' }">Kill</vui-button>
      <vui-button :params="{ target: 'misc', action: 'gib' }">Gib</vui-button>
      <vui-button :params="{ target: 'misc', action: 'dust' }">Dust</vui-button>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  }
}
</script>

<style lang="scss" scoped>
table {
  width: 100%;
  text-align: center;
}
tr {
  line-height: 135%;
}
</style>
