// tgui/packages/tgui/interfaces/PlayerPanel.tsx
import { BooleanLike } from 'tgui-core/react';
import { useBackend, useLocalState } from '../backend';
import { Input, Box, Button, Section, Table } from 'tgui-core/components';
import { Window } from '../layouts';

export type PanelData = {
  holder_ref: string;
  is_mod: BooleanLike;
  players: Player[];
};

type Player = {
  ckey: BooleanLike;
  ref: string;
  name: string;
  real_name: string;
  assigment: string;
  key: string;
  ip: string;
  connected: BooleanLike;
  antag: number; // 0 (non-antag), 1 (special role) or 2 (antag)
  age: any; // string or number
};

export const PlayerPanel = (props) => {
  const { act, data } = useBackend<PanelData>();

  const [searchTerm, setSearchTerm] = useLocalState<string>(
    `searchTerm`,
    ``
  );

  return (
    <Window theme="admin">
      <Window.Content scrollable>
        <Section
          title="Players"
          buttons={
            <Input
              autoFocus
              autoSelect
              placeholder="Search by ckey, name, or assignment"
              width="40vw"
              maxLength={512}
              onInput={(e, value) => {
                setSearchTerm(value);
              }}
              value={searchTerm}
            />
          }>
          <Table>
            <Table.Row header>
              <Table.Cell>Name</Table.Cell>
              <Table.Cell>Assignment</Table.Cell>
              <Table.Cell>Key</Table.Cell>
              {data.is_mod ? <Table.Cell>Age</Table.Cell> : ''}
              {data.is_mod ? <Table.Cell>Antag</Table.Cell> : ''}
              <Table.Cell textAlign="right">Actions</Table.Cell>
            </Table.Row>
            {data.players
              .filter(
                (player) =>
                  player.key?.toLowerCase().indexOf(searchTerm.toLowerCase()) >
                    -1 ||
                  player.name?.toLowerCase().indexOf(searchTerm.toLowerCase()) >
                    -1 ||
                  player.real_name
                    ?.toLowerCase()
                    .indexOf(searchTerm.toLowerCase()) > -1 ||
                  player.assigment
                    ?.toLowerCase()
                    .indexOf(searchTerm.toLowerCase()) > -1
              )
              .map((player) => (
                <Table.Row key={player.name}>
                  <Table.Cell>
                    {player.name === player.real_name ||
                    player.assigment === 'NA'
                      ? player.name
                      : player.real_name}
                  </Table.Cell>
                  <Table.Cell>
                    {player.assigment === 'NA'
                      ? player.real_name
                      : player.assigment}
                  </Table.Cell>
                  <Table.Cell>
                    {player.key}
                    {!player.connected ? ' (DC)' : ''}
                  </Table.Cell>
                  <Table.Cell>{data.is_mod ? player.age : ''}</Table.Cell>
                  <Table.Cell>
                    {player.antag === 2
                      ? 'Added by Gamemode'
                      : player.antag === 1
                        ? 'Added by Admin'
                        : player.antag === 0
                          ? 'No'
                          : 'NA'}
                  </Table.Cell>
                  <Table.Cell>
                    <Box textAlign="right">
                      <Button
                        content="PP"
                        onClick={() =>
                          act('show_player_panel', {
                            show_player_panel: player.ref,
                          })
                        }
                      />
                      <Button
                        content="PM"
                        onClick={() =>
                          act('private_message', {
                            private_message: player.ref,
                          })
                        }
                      />
                      <Button
                        content="VV"
                        onClick={() =>
                          act('view_variables', {
                            view_variables: player.ref,
                          })
                        }
                      />
                      <Button
                        content="SM"
                        onClick={() =>
                          act('subtle_message', { subtle_message: player.ref })
                        }
                      />
                      <Button
                        content="N"
                        onClick={() => act('notes', { ckey: player.key })}
                      />
                      <Button
                        content="TP"
                        onClick={() =>
                          act('traitor_panel', { traitor_panel: player.ref })
                        }
                      />
                      <Button
                        content="JMP"
                        onClick={() => act('jump_to', { jump_to: player.ref })}
                      />
                      <Button
                        content="WND"
                        onClick={() => act('wind', { wind: player.ref })}
                      />
                    </Box>
                  </Table.Cell>
                </Table.Row>
              ))}
          </Table>
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/admin/player-panel.vue
<template>
  <div>
    <vui-button :unsafe-params="{src: s.holder_ref, check_antagonist: 1}">Check antagonists</vui-button>
    <vui-input-search style="float: right;" :input="players_filtered" v-model="search_results" :keys="['name', 'real_name', 'assigment', 'key', 'ip']" autofocus/>
    <div class="table">
      <div class="header">
        <div class="header-item">Name</div>
        <div class="header-item">Assignment</div>
        <div class="header-item">Key</div>
        <div class="header-item" v-if="s.ismod">Age</div>
        <div class="header-item" v-if="s.ismod">Antag</div>
        <div class="header-item">Actions</div>
      </div>
      <div class="player" v-for="p in search_results" :key="p.ref">
        <div class="item">
          <template v-if="(p.name == p.real_name) || (p.assigment == 'NA')">{{p.name}}</template>
          <vui-tooltip v-else :label="p.name">{{p.real_name}}</vui-tooltip>
        </div>
        <div class="item">
          <template v-if="p.assigment == 'NA'">{{p.real_name}}</template>
          <template v-else>{{p.assigment}}</template>
        </div>
        <div class="item">
          <template v-if="!s.ismod">
            {{p.key}}<span v-if="!p.connected"> (DC)</span>
          </template>
          <vui-tooltip v-else>
            <template v-slot:label>{{p.key}}<span v-if="!p.connected"> (DC)</span></template>
            {{p.ip}}
          </vui-tooltip>
        </div>
        <div class="item" v-if="s.ismod">{{p.age}}</div>
        <div class="item" v-if="s.ismod">
          <span v-if="p.antag == -1">NA</span>
          <span v-else-if="p.antag == 0">No</span>
          <span class="red" v-if="p.antag == 1"><vui-tooltip label="ADD">This antag was added by admin.</vui-tooltip></span>
          <span class="red" v-if="p.antag == 2"><vui-tooltip label="GM">This antag was added by gamemode.</vui-tooltip></span>
        </div>
        <div class="item" style="text-align: right;">
          <vui-button :unsafe-params="{src: s.holder_ref, adminplayeropts: p.ref}">PP</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, priv_msg: p.ref}">PM</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, subtlemessage: p.ref}">SM</vui-button>
          <vui-button :unsafe-params="{_src_: 'vars', Vars: p.ref}">VV</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, mob: p.ref, notes: 'show'}">N</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, traitor: p.ref}">TP</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, adminplayerobservejump: p.ref}">JMP</vui-button>
          <vui-button :unsafe-params="{src: s.holder_ref, admin_wind_player: p.ref}">WIND</vui-button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      search_results: [],
      s: this.$root.$data.state
    }
  },
  computed: {
    players_filtered() {
      return Object.values(this.s.players).filter(x => x)
    }
  }
}
</script>

<style lang="scss" scoped>
.table {
  display: table;
  width: 100%;

  .header {
    text-align: center;
    font-weight: bold;
  }
  .header, .player {
    display: table-row;
    .header-item, .item {
      display: table-cell;
      padding: 1px;
    }
  }

}
</style>
