// tgui/packages/tgui/interfaces/Canister.tsx
import { useBackend } from '../backend';
import { Section, Box, ProgressBar, Knob, Button, LabeledList } from 'tgui-core/components';
import { Window } from '../layouts';
import { BooleanLike } from 'tgui-core/react';

export type CanisterData = {
  name: string;
  canLabel: BooleanLike;
  portConnected: BooleanLike;
  tankPressure: number;
  releasePressure: number;
  minReleasePressure: number;
  maxReleasePressure: number;
  valveOpen: BooleanLike;
  hasHoldingTank: BooleanLike;
  holdingTank: Tank;
};

type Tank = {
  name: string;
  tankPressure: number;
};

export const Canister = (props) => {
  const { act, data } = useBackend<CanisterData>();
  let port_string = data.portConnected ? 'Connected' : 'Disconnected';

  return (
    <Window>
      <Window.Content scrollable>
        <Section
          title="Tank Status"
          buttons={
            !!data.canLabel && (
              <Button
                icon="pencil-alt"
                content="Relabel"
                onClick={() => act('relabel')}
              />
            )
          }>
          <LabeledList>
            <LabeledList.Item label="Tank Label">{data.name}</LabeledList.Item>
            <LabeledList.Item label="Tank Pressure">
              {data.tankPressure} kPa
            </LabeledList.Item>
            <LabeledList.Item label="Port Status">
              {port_string}
            </LabeledList.Item>
          </LabeledList>
        </Section>
        <Section
          title="Holding Tank Status"
          buttons={
            !!data.hasHoldingTank && (
              <Button
                icon="eject"
                color={data.valveOpen && 'danger'}
                content="Eject"
                onClick={() => act('remove_tank')}
              />
            )
          }>
          {data.hasHoldingTank ? (
            <HoldingTankWindow />
          ) : (
            <Box>No holding tank inserted.</Box>
          )}
        </Section>
        <Section title="Release Valve Status">
          <Box>
            Release Pressure:
            <ProgressBar
              ranges={{
                good: [data.maxReleasePressure * 0.8, data.maxReleasePressure],
                average: [
                  data.maxReleasePressure * 0.4,
                  data.maxReleasePressure * 0.8,
                ],
                bad: [0, data.maxReleasePressure * 0.4],
              }}
              value={data.releasePressure}
              minValue={data.minReleasePressure}
              maxValue={data.maxReleasePressure}
            />
            <Section textAlign="center">
              <Button
                content="Open"
                icon="lock-open"
                disabled={data.valveOpen}
                onClick={() => act('toggle')}
              />
              <Button
                content="Close"
                icon="lock"
                disabled={!data.valveOpen}
                onClick={() => act('toggle')}
              />
            </Section>
            <Knob
              size={1.25}
              color={!!data.valveOpen && 'yellow'}
              value={data.releasePressure}
              unit="kPa"
              minValue={data.minReleasePressure}
              maxValue={data.maxReleasePressure}
              step={5}
              stepPixelSize={1}
              onDrag={(e, value) =>
                act('pressure', {
                  pressure: value,
                })
              }
            />
          </Box>
        </Section>
      </Window.Content>
    </Window>
  );
};

export const HoldingTankWindow = (props) => {
  const { act, data } = useBackend<CanisterData>();
  return (
    <Section>
      <LabeledList>
        <LabeledList.Item label="Tank Label">
          {data.holdingTank.name}
        </LabeledList.Item>
        <LabeledList.Item label="Tank Pressure">
          {data.holdingTank.tankPressure} kPa
        </LabeledList.Item>
      </LabeledList>
    </Section>
  );
};

// vueui/src/components/view/machinery/atmospherics/canister.vue
<template>
  <div>
    <h3>Tank Status</h3>
    <vui-group>
      <vui-group-item label="Tank Label:">
        {{ name }}
        <vui-button class="float-right" icon="pencil-alt" :params="{ relabel: 1 }" :disabled="!canLabel"
          >Relabel</vui-button
        >
      </vui-group-item>
      <vui-group-item label="Tank Pressure:"> {{ tankPressure }} kPa </vui-group-item>
      <vui-group-item label="Port Status:">
        <span :class="portConnected ? good : average">{{ portConnected ? 'Connected' : 'Disconnected' }}</span>
      </vui-group-item>

      <vui-group-row>
        <h3>Holding Tank Status</h3>
      </vui-group-row>
      <template v-if="hasHoldingTank">
        <vui-group-item label="Tank Label:">
          {{ holdingTank.name
          }}<vui-button class="float-right" icon="eject" :params="{ remove_tank: 1 }">Eject</vui-button>
        </vui-group-item>

        <vui-group-item label="Tank Pressure:">{{ holdingTank.tankPressure }} kPa</vui-group-item>
      </template>
      <vui-group-item v-else
        ><span class="average"><i>No holding tank inserted.</i></span></vui-group-item
      >

      <vui-group-row>
        <h3>Release Valve Status</h3>
      </vui-group-row>

      <vui-group-item label="Release Pressure:">
        <vui-progress
          style="width: 100%;"
          :value="releasePressure"
          :min="minReleasePressure"
          :max="maxReleasePressure"
        />
        <div style="clear: both; padding-top: 4px;">
          <vui-input-numeric
            width="5em"
            v-model="releasePressure"
            :button-count="4"
            :min="minReleasePressure"
            :max="maxReleasePressure"
            @input="$atc({ pressure_set: releasePressure })"
            >{{ releasePressure }} kPa&nbsp;</vui-input-numeric
          >
        </div>
      </vui-group-item>

      <vui-group-item label="Release Valve:">
        <vui-button icon="lock-open" :params="{ toggle: 1 }" :class="{ selected: valveOpen }">Open</vui-button>
        <vui-button icon="lock" :params="{ toggle: 1 }" :class="{ selected: !valveOpen }">Close</vui-button>
      </vui-group-item>
    </vui-group>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state
  },
}
</script>
