// tgui/packages/tgui/interfaces/SuspensionGenerator.tsx
import { BooleanLike } from '../../common/react';
import { useBackend } from '../backend';
import { Button, LabeledList, ProgressBar, Section } from '../components';
import { Window } from '../layouts';

export type SuspensionData = {
  charge: number;
  fieldtype: string;
  fieldtypes: Field[];
  active: BooleanLike;
  anchored: BooleanLike;
};

type Field = {
  name: string;
  type: string;
};

export const SuspensionGenerator = (props) => {
  const { act, data } = useBackend<SuspensionData>();

  return (
    <Window resizable>
      <Window.Content scrollable>
        <Section title="Overview">
          <LabeledList>
            <LabeledList.Item
              label="Cell Charge"
              buttons={
                <Button
                  content="Toggle Field"
                  disabled={!data.anchored}
                  icon={data.active ? 'times' : 'power-off'}
                  color={data.active ? 'good' : 'bad'}
                  tooltip="Cannot be enabled while unanchored."
                  onClick={() => act('togglefield')}
                />
              }>
              <ProgressBar
                ranges={{
                  good: [75, 100],
                  average: [30, 75],
                  bad: [0, 30],
                }}
                value={data.charge}
                minValue={0}
                maxValue={100}>
                {data.charge}%
              </ProgressBar>
            </LabeledList.Item>
            <LabeledList.Item label="Field Status">
              {data.active ? 'Enabled' : 'Disabled'}
            </LabeledList.Item>
          </LabeledList>
        </Section>
        <Section title="Field Types">
          <LabeledList>
            {data.fieldtypes.map((field) => (
              <LabeledList.Item key={field.name} label={field.name}>
                <Button
                  content={
                    data.fieldtype === field.type ? 'Selected' : 'Select'
                  }
                  color={data.fieldtype === field.type ? 'good' : ''}
                  onClick={() => act('fieldtype', { fieldtype: field.type })}
                />
              </LabeledList.Item>
            ))}
          </LabeledList>
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/machinery/xenoarchaeology/suspensiongenerator.vue
<template>
  <div>
    <div>
      <h3>Overview</h3>
      <vui-group>
        <vui-group-item label="Cell Charge:"><vui-progress :class="progressClass(charge)" :value="charge">{{ charge }}%</vui-progress></vui-group-item>
        <vui-group-item label="Field Status:">{{ active ? "Active" : "Disabled" }}</vui-group-item>
        <vui-group-item label="Toggle Field:"><vui-button :disabled="locked || !anchored" :params="{togglefield: 1}">{{ locked ? "Toggle Field (Locked)" : anchored ? "Toggle Field" : "Toggle Field (Unanchored)"}}</vui-button></vui-group-item>
      </vui-group>
    </div>
    <div>
      <h3>Field Types:</h3>
      <div v-for="(desc, field) in fieldtypes" :key="field">
        <vui-button :class="{'button' : 1, 'selected' : fieldtype == field}" :params="{ fieldtype: field }">{{ desc }}</vui-button>
      </div>
    </div>
    <footer>Always wear safety gear and consult a field manual before operation.</footer>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  },
  methods: {
    progressClass(value) {
      if (value <= 50) {
        return "bad"
      }
      else if (value <= 90) {
        return "average"
      }
      else {
        return "good"
      }
    }
  }
}
</script>
