// tgui/packages/tgui/interfaces/GhostSpawner.tsx
import { BooleanLike } from '../../common/react';
import { useBackend, useLocalState } from '../backend';
import { Button, Input, Section, Table, Tabs } from '../components';
import { Window } from '../layouts';

export type SpawnerData = {
  spawners: Spawner[];
  categories: string[];
};

type Spawner = {
  short_name: string;
  name: string;
  desc: string;
  type: string;
  cant_spawn: BooleanLike;
  can_edit: BooleanLike;
  can_jump_to: BooleanLike;
  enabled: BooleanLike;
  count: number;
  max_count: number;
  spawn_atoms: any;
  tags: string[];
  spawnpoints: string[];
};

export const GhostSpawner = (props, context) => {
  const { act, data } = useBackend<SpawnerData>(context);
  const [tab, setTab] = useLocalState(context, 'tab', 'All');
  const [searchTerm, setSearchTerm] = useLocalState<string>(
    context,
    `searchTerm`,
    ``
  );

  return (
    <Window resizable width={1000} height={700}>
      <Window.Content scrollable>
        <Section
          title="Spawners"
          buttons={
            <Input
              autoFocus
              autoSelect
              placeholder="Search by name"
              width="40vw"
              maxLength={512}
              onInput={(e, value) => {
                setSearchTerm(value);
              }}
              value={searchTerm}
            />
          }>
          <Tabs>
            <Tabs.Tab selected={tab === 'All'} onClick={() => setTab('All')}>
              All
            </Tabs.Tab>
            {data.categories.map((cat) => (
              <Tabs.Tab
                key={cat}
                selected={tab === cat}
                onClick={() => setTab(cat)}>
                {cat}
              </Tabs.Tab>
            ))}
          </Tabs>
          <Table preserveWhitespace>
            <Table.Row>
              <Table.Cell>Name</Table.Cell>
              <Table.Cell>Description</Table.Cell>
              <Table.Cell>Available Slots</Table.Cell>
              <Table.Cell>Actions</Table.Cell>
            </Table.Row>
            {data.spawners
              .filter(
                (S) =>
                  S.name.toLowerCase().indexOf(searchTerm.toLowerCase()) > -1
              )
              .map(
                (spawner) =>
                  (spawner.tags.indexOf(tab) || tab === 'All') && (
                    <Table.Row key={spawner.short_name}>
                      <Table.Cell>{spawner.name}</Table.Cell>
                      <Table.Cell>{spawner.desc}</Table.Cell>
                      <Table.Cell>
                        {spawner.max_count > 0
                          ? spawner.max_count -
                          spawner.count +
                          ' / ' +
                          spawner.max_count
                          : spawner.spawn_atoms}
                      </Table.Cell>
                      <Table.Cell inline nowrap>
                        <Button
                          content="Spawn"
                          color="good"
                          icon="star"
                          disabled={spawner.cant_spawn}
                          onClick={() =>
                            act('spawn', { spawn: spawner.short_name })
                          }
                        />
                        {spawner.can_jump_to ? (
                          <Button
                            content="J"
                            onClick={() =>
                              act('jump_to', { jump_to: spawner.short_name })
                            }
                          />
                        ) : (
                          ''
                        )}
                        {spawner.can_edit ? (
                          <>
                            <Button
                              content="E"
                              disabled={spawner.enabled}
                              onClick={() =>
                                act('enable', { enable: spawner.short_name })
                              }
                            />
                            <Button
                              content="D"
                              disabled={!spawner.enabled}
                              onClick={() =>
                                act('disable', { disable: spawner.short_name })
                              }
                            />
                          </>
                        ) : (
                          ' '
                        )}
                      </Table.Cell>
                    </Table.Row>
                  )
              )}
          </Table>
        </Section>
      </Window.Content>
    </Window>
  );
};

// vueui/src/components/view/misc/ghostspawner.vue
<template>
  <div>
    <div class="tagselector" v-show="!spawnpoint">
      <vui-button v-for="(amount,tag) in tags" :key="tag" v-on:click="current_tag = tag" v-bind:class="{ selected: current_tag == tag}">{{tag}} ({{amount}})</vui-button>
    </div>
    <hr v-show="!spawnpoint">
    <table>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Available Slots</th>
        <th class="taction">Actions</th>
      </tr>
      <tr v-for="(data,index) in spawners" :key="index" v-show="showEntry(data)">
        <td>{{data.name}}</td>
        <td>{{data.desc}}</td>
        <td v-if="data.max_count > 0">{{data.max_count - data.count}} / {{data.max_count}}</td>
        <td v-else>&infin;</td>
        <td>
          <vui-button :disabled="(data.cant_spawn !== 0)" :params="{spawn: index, spawnpoint: spawnpoint}" icon="star">Spawn</vui-button> 
          <vui-button v-if="data.can_edit == 1" :disabled="(data.enabled == 1)" :params="{enable: index}">Enable</vui-button> 
          <vui-button v-if="data.can_edit == 1" :disabled="(data.enabled == 0)" :params="{disable: index}">Disable</vui-button> 
        </td>
      </tr>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return this.$root.$data.state;
  },
  computed: {
    tags: function() {
      let ctags = {}
      ctags.All = 0
      let s
      for (s in this.spawners){
        ctags.All += 1
        let spawner = this.spawners[s]
        let t;
        for (t in spawner.tags){
          let tag_name = spawner.tags[t]
          if(ctags.hasOwnProperty(tag_name)){
            ctags[tag_name] += 1
          } else {
            ctags[tag_name] = 1
          }
        }
      }
      return ctags
    }
  }, methods:{
    showEntry: function(data) {
      if(!this.spawnpoint){
        //if we dont have a spawnpoint-filter set, then look at the tag filter
        return !data.tags.indexOf(this.current_tag) || this.current_tag == 'All'
      } else {
        //if we have a spawnpoint filter set, filter by spawnpoints
        if(!data.hasOwnProperty('spawnpoints'))
          return false
        return !data.spawnpoints.indexOf(this.spawnpoint)
      }
    }
  }
}
</script>

<style lang="scss" scoped>
  table {
    width: 100%;
    th {
      font-weight: bold;
    }
    th, td {
      text-align: center;
    }
    .taction {
      width: 200px;
    }
  }
  .tagselector {
    display: flex;
  }
</style>
